#!/bin/sh
# Generated by brain.deployment.release.render_update. Do not edit: edit the plan and
# regenerate, or the script and the plan disagree and the plan is the tested one.
set -eu

BRAIN_PROFILE="${1:?usage: update.sh <profile> <release tag>}"
BRAIN_RELEASE="${2:?usage: update.sh <profile> <release tag>}"
BRAIN_HOME="/opt/brain"
BRAIN_REPOSITORY="ghcr.io/rpsj2230/verz-brain-v2.0"
BRAIN_RELEASE_URL="${BRAIN_RELEASE_URL:?set BRAIN_RELEASE_URL to the release archive}"

say() { printf "%s\n" "$1"; }
fail() { printf "%s\n" "$1" >&2; exit 1; }
running_images() {
  docker compose $BRAIN_COMPOSE_FILES ps --quiet | while read -r one; do
    docker inspect --format "{{.Config.Image}}" "$one"
  done
}
off_the_pin() {
  running_images | grep -F "$BRAIN_REPOSITORY:" | grep -vxF "$BRAIN_REPOSITORY:$BRAIN_RELEASE"
}

case "$BRAIN_PROFILE" in
  lite) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.lite.yml" ;;
  standard) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.yml -f /opt/brain/docker-compose.worker.yml -f /opt/brain/docker-compose.parse-worker.yml -f /opt/brain/docker-compose.objectstore.yml -f /opt/brain/docker-compose.keycloak.yml -f /opt/brain/docker-compose.inference.yml" ;;
  full) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.yml -f /opt/brain/docker-compose.worker.yml -f /opt/brain/docker-compose.parse-worker.yml -f /opt/brain/docker-compose.objectstore.yml -f /opt/brain/docker-compose.keycloak.yml -f /opt/brain/docker-compose.langfuse.yml -f /opt/brain/docker-compose.inference.yml -f /opt/brain/docker-compose.automation.yml" ;;
  *) fail "unknown profile; one of: lite standard full" ;;
esac

say "Updating the $BRAIN_PROFILE profile in $BRAIN_HOME to $BRAIN_RELEASE."

# step 1 of 10: refuse a tag that pins nothing
say "step 1 of 10: refuse a tag that pins nothing"
test "$BRAIN_RELEASE" != "latest" || fail "latest is not a release tag: updating to it stops this install being pinned, so the next pull changes the version with nobody deciding anything. Name the release you mean to install"

# step 2 of 10: check this directory holds an install
say "step 2 of 10: check this directory holds an install"
test -s "/opt/brain/RELEASE" || fail "there is no release marker here, so this directory is not an install this script can move. Install first"
test -s "/opt/brain/.env" || fail "there is no environment file here, and the pin is written into it. Install first, or put the file back from your own copy of it"

# step 3 of 10: record the release this update replaces
if test "$(cat "/opt/brain/RELEASE")" = "$BRAIN_RELEASE"; then
  say "step 3 of 10: record the release this update replaces - already done, skipping"
else
  say "step 3 of 10: record the release this update replaces"
  cp "/opt/brain/RELEASE" "/opt/brain/PREVIOUS_RELEASE"
fi

# step 4 of 10: download and unpack the release
if test -f "/opt/brain/RELEASE" && test "$(cat "/opt/brain/RELEASE")" = "$BRAIN_RELEASE"; then
  say "step 4 of 10: download and unpack the release - already done, skipping"
else
  say "step 4 of 10: download and unpack the release"
  curl -fsSL "$BRAIN_RELEASE_URL" -o "/opt/brain/release.tar.gz"
  tar -xzf "/opt/brain/release.tar.gz" -C "/opt/brain" --strip-components=1
  printf "%s\n" "$BRAIN_RELEASE" > "/opt/brain/RELEASE"
fi

# step 5 of 10: change into the release directory
say "step 5 of 10: change into the release directory"
cd "/opt/brain" || fail "the release did not unpack into /opt/brain"

# step 6 of 10: create the settings the containers mount
if test -f "/opt/brain/settings/automation/egress.conf" && test -f "/opt/brain/settings/langfuse/clickhouse-memory.xml" && test -f "/opt/brain/settings/seaweedfs/provision.sh" && test -f "/opt/brain/settings/seaweedfs/s3.json"; then
  say "step 6 of 10: create the settings the containers mount - already done, skipping"
else
  say "step 6 of 10: create the settings the containers mount"
  mkdir -p "/opt/brain/settings/automation" "/opt/brain/settings/langfuse" "/opt/brain/settings/seaweedfs"
  test -f "/opt/brain/settings/automation/egress.conf" || cp "/opt/brain/ops/automation/egress.conf" "/opt/brain/settings/automation/egress.conf"
  test -f "/opt/brain/settings/langfuse/clickhouse-memory.xml" || cp "/opt/brain/ops/langfuse/clickhouse-memory.xml" "/opt/brain/settings/langfuse/clickhouse-memory.xml"
  test -f "/opt/brain/settings/seaweedfs/provision.sh" || cp "/opt/brain/ops/seaweedfs/provision.sh" "/opt/brain/settings/seaweedfs/provision.sh"
  test -f "/opt/brain/settings/seaweedfs/s3.json" || cp "/opt/brain/ops/seaweedfs/s3.json" "/opt/brain/settings/seaweedfs/s3.json"
fi

# step 7 of 10: pin the image this install runs
if grep -qxF "APP_IMAGE=$BRAIN_REPOSITORY:$BRAIN_RELEASE" "/opt/brain/.env"; then
  say "step 7 of 10: pin the image this install runs - already done, skipping"
else
  say "step 7 of 10: pin the image this install runs"
  umask 077
  {
    grep -v "^APP_IMAGE=" "/opt/brain/.env" || true
    printf "APP_IMAGE=%s\n" "$BRAIN_REPOSITORY:$BRAIN_RELEASE"
  } > "/opt/brain/.env.pinned"
  mv "/opt/brain/.env.pinned" "/opt/brain/.env"
fi

# step 8 of 10: pull the image this release publishes
if docker image inspect "$BRAIN_REPOSITORY:$BRAIN_RELEASE" >/dev/null 2>&1; then
  say "step 8 of 10: pull the image this release publishes - already done, skipping"
else
  say "step 8 of 10: pull the image this release publishes"
  docker compose $BRAIN_COMPOSE_FILES pull --quiet
fi

# step 9 of 10: recreate the containers on the pinned image
if running_images | grep -qxF "$BRAIN_REPOSITORY:$BRAIN_RELEASE" && test -z "$(off_the_pin)"; then
  say "step 9 of 10: recreate the containers on the pinned image - already done, skipping"
else
  say "step 9 of 10: recreate the containers on the pinned image"
  docker compose $BRAIN_COMPOSE_FILES up -d
fi

# step 10 of 10: wait for the application to report ready
say "step 10 of 10: wait for the application to report ready"
for _ in $(seq 1 60); do
  docker compose $BRAIN_COMPOSE_FILES exec -T app python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen("http://127.0.0.1:8000/health/ready",timeout=4).status==200 else 1)' && break
  sleep 5
done
docker compose $BRAIN_COMPOSE_FILES exec -T app python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen("http://127.0.0.1:8000/health/ready",timeout=4).status==200 else 1)' || fail "the application never reported ready"

say "Done. This install is on $BRAIN_RELEASE and pinned to it."
