#!/bin/sh
# Generated by brain.deployment.vault_setup.render_apply. Do not edit: edit the module and
# regenerate with `uv run python -m brain.deployment.vault_setup > ops/openbao/apply-release.sh`,
# or the script and the tested module disagree.
#
# Applies this release's vault engines, policies, token role and credential slots to the
# running vault, reads each back, and fails loudly if one did not take. Idempotent: a
# release that changed nothing changes nothing. Run by the installer (as root), by the
# update and the rollback, by the automatic deploy (ops/deploy/brain-deploy) and by the
# switch an older install makes. See brain.deployment.vault_setup.
#
# Usage: sh ops/openbao/apply-release.sh [--check]
#   --check  change nothing; exit 0 only when everything is already in force
# The token is BAO_TOKEN when set, otherwise the deploy token file. Exit 0: in force.
# Exit 3: no deploy token on this server (an install that has not moved yet).
# Any other exit: something did not take, and the lines above it say what.

set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
CONTAINER="${BRAIN_VAULT_CONTAINER:-brain-vault}"
TOKEN_FILE="${BRAIN_VAULT_DEPLOY_TOKEN_FILE:-/etc/brain-vault/deploy.token}"
CHECK_ONLY=no
test "${1:-}" = "--check" && CHECK_ONLY=yes
NOT_IN_FORCE=0

say() { printf "vault: %s\n" "$1"; }
fail() { printf "vault: %s\n" "$1" >&2; exit 1; }
missing() { printf "vault: not in force: %s\n" "$1" >&2; NOT_IN_FORCE=$((NOT_IN_FORCE + 1)); }

if test -z "${BAO_TOKEN:-}"; then
  if ! test -r "$TOKEN_FILE"; then
    printf "vault: %s\n" "there is no deploy token at $TOKEN_FILE, so this release's vault changes were not applied. An install made before the vault opened itself moves with ops/openbao/switch-to-auto-unseal.sh" >&2
    exit 3
  fi
  BAO_TOKEN="$(cat "$TOKEN_FILE")"
fi
export BAO_TOKEN
bao_() { docker exec -e BAO_TOKEN -e BAO_ADDR=http://127.0.0.1:8200 "$CONTAINER" bao "$@" </dev/null; }
bao_in() { docker exec -i -e BAO_TOKEN -e BAO_ADDR=http://127.0.0.1:8200 "$CONTAINER" bao "$@"; }

docker exec -e BAO_ADDR=http://127.0.0.1:8200 "$CONTAINER" bao status >/dev/null 2>&1 || fail "$CONTAINER is not running, or is sealed. It opens itself from its seal key; if it stays sealed, read docker logs $CONTAINER and ops/openbao/UNSEAL.md"
bao_ token lookup >/dev/null 2>&1 || fail "the vault refused the token this ran with. If it is the deploy token it has lapsed or been revoked: ops/openbao/UNSEAL.md, under In an emergency, makes a new one"

# The engines, enabled where missing and never removed.
ENGINES_NOW="$(bao_ secrets list)" || fail "the vault would not list its engines"
for engine in providers webhooks connector_keys template_signing; do
  case "$ENGINES_NOW" in
    *"$engine/ "*) ;;
    *) if test "$CHECK_ONLY" = yes; then missing "the $engine engine"; else bao_ secrets enable -path="$engine" kv-v2 >/dev/null || fail "the vault would not enable the $engine engine"; fi ;;
  esac
done
ENGINES_NOW="$(bao_ secrets list)" || fail "the vault would not list its engines"
for engine in providers webhooks connector_keys template_signing; do
  case "$ENGINES_NOW" in *"$engine/ "*) ;; *) test "$CHECK_ONLY" = yes || missing "the $engine engine" ;; esac
done

# Every policy file, written where the vault holds different text, then read back. The
# deploy token's own policy is read-only to it, so a change there says what it needs.
POLICIES=0
for file in "$HERE"/policies/*.hcl; do
  name="$(basename "$file" .hcl)"
  want="$(tr -d '\015' < "$file")"
  have="$(bao_ read -field=policy "sys/policies/acl/$name" 2>/dev/null || true)"
  if test "$have" != "$want" && test "$CHECK_ONLY" = no; then
    printf "%s\n" "$want" | bao_in policy write "$name" - >/dev/null 2>&1 || {
      test "$name" = "deploy" && fail "this release changes the deploy token's own policy, which the deploy token may not load itself. Load it with a root token: ops/openbao/UNSEAL.md, under In an emergency"
      fail "the vault would not load the $name policy"
    }
    have="$(bao_ read -field=policy "sys/policies/acl/$name" 2>/dev/null || true)"
  fi
  test "$have" = "$want" || missing "the $name policy"
  POLICIES=$((POLICIES + 1))
done

# The token role a connector run's token is minted against.
role_ok() { test "$(bao_ read -field=allowed_policies auth/token/roles/connector-run 2>/dev/null)" = "[connector-run]" && test "$(bao_ read -field=orphan auth/token/roles/connector-run 2>/dev/null)" = "false" && test "$(bao_ read -field=renewable auth/token/roles/connector-run 2>/dev/null)" = "false" && test "$(bao_ read -field=token_no_default_policy auth/token/roles/connector-run 2>/dev/null)" = "true" && test "$(bao_ read -field=token_explicit_max_ttl auth/token/roles/connector-run 2>/dev/null)" = "3600"; }
if ! role_ok; then
  if test "$CHECK_ONLY" = no; then
    bao_ write auth/token/roles/connector-run allowed_policies=connector-run orphan=false renewable=false token_no_default_policy=true token_explicit_max_ttl=3600 >/dev/null || fail "the vault would not define the connector-run token role"
  fi
  role_ok || missing "the connector-run token role"
fi

# Every connected source's slot: its scopes, and no key.
slot_ok() { test "$(bao_ read -field=custom_metadata "connector_keys/metadata/$1" 2>/dev/null)" = "$2"; }
if ! slot_ok freshdesk 'map[not_requested:an admin key, which can change SLAs and delete tickets scopes:an agent API key with read access]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=an agent API key with read access' -custom-metadata='not_requested=an admin key, which can change SLAs and delete tickets' freshdesk >/dev/null || fail "the vault would not define the credential slot for freshdesk"
  fi
  slot_ok freshdesk 'map[not_requested:an admin key, which can change SLAs and delete tickets scopes:an agent API key with read access]' || missing "the credential slot for freshdesk"
fi
if ! slot_ok google_analytics 'map[not_requested:analytics.edit; domain-wide delegation scopes:analytics.readonly; Viewer on the one property]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=analytics.readonly; Viewer on the one property' -custom-metadata='not_requested=analytics.edit; domain-wide delegation' google_analytics >/dev/null || fail "the vault would not define the credential slot for google_analytics"
  fi
  slot_ok google_analytics 'map[not_requested:analytics.edit; domain-wide delegation scopes:analytics.readonly; Viewer on the one property]' || missing "the credential slot for google_analytics"
fi
if ! slot_ok google_drive 'map[not_requested:domain-wide delegation scopes:Viewer on the one folder shared with it]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=Viewer on the one folder shared with it' -custom-metadata='not_requested=domain-wide delegation' google_drive >/dev/null || fail "the vault would not define the credential slot for google_drive"
  fi
  slot_ok google_drive 'map[not_requested:domain-wide delegation scopes:Viewer on the one folder shared with it]' || missing "the credential slot for google_drive"
fi
if ! slot_ok hubspot 'map[not_requested:crm.objects.*.write; anything touching settings scopes:crm.objects.contacts.read; crm.objects.deals.read]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=crm.objects.contacts.read; crm.objects.deals.read' -custom-metadata='not_requested=crm.objects.*.write; anything touching settings' hubspot >/dev/null || fail "the vault would not define the credential slot for hubspot"
  fi
  slot_ok hubspot 'map[not_requested:crm.objects.*.write; anything touching settings scopes:crm.objects.contacts.read; crm.objects.deals.read]' || missing "the credential slot for hubspot"
fi
if ! slot_ok laravel 'map[not_requested:SELECT on tables; any write scopes:SELECT on the allowlisted views only]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=SELECT on the allowlisted views only' -custom-metadata='not_requested=SELECT on tables; any write' laravel >/dev/null || fail "the vault would not define the credential slot for laravel"
  fi
  slot_ok laravel 'map[not_requested:SELECT on tables; any write scopes:SELECT on the allowlisted views only]' || missing "the credential slot for laravel"
fi
if ! slot_ok lark_base 'map[not_requested:base:record:write; drive:drive scopes:bitable:app:readonly; base:record:read]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=bitable:app:readonly; base:record:read' -custom-metadata='not_requested=base:record:write; drive:drive' lark_base >/dev/null || fail "the vault would not define the credential slot for lark_base"
  fi
  slot_ok lark_base 'map[not_requested:base:record:write; drive:drive scopes:bitable:app:readonly; base:record:read]' || missing "the credential slot for lark_base"
fi
if ! slot_ok lark_wiki 'map[not_requested:docs:document edit scopes scopes:wiki:wiki:readonly]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=wiki:wiki:readonly' -custom-metadata='not_requested=docs:document edit scopes' lark_wiki >/dev/null || fail "the vault would not define the credential slot for lark_wiki"
  fi
  slot_ok lark_wiki 'map[not_requested:docs:document edit scopes scopes:wiki:wiki:readonly]' || missing "the credential slot for lark_wiki"
fi
if ! slot_ok staff_source 'map[not_requested:any write; for LDAP an administrator or an account that may reset passwords or groups scopes:read on the staff directory only; for LDAP a service account that may bind and search and nothing more]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=read on the staff directory only; for LDAP a service account that may bind and search and nothing more' -custom-metadata='not_requested=any write; for LDAP an administrator or an account that may reset passwords or groups' staff_source >/dev/null || fail "the vault would not define the credential slot for staff_source"
  fi
  slot_ok staff_source 'map[not_requested:any write; for LDAP an administrator or an account that may reset passwords or groups scopes:read on the staff directory only; for LDAP a service account that may bind and search and nothing more]' || missing "the credential slot for staff_source"
fi
if ! slot_ok xero 'map[not_requested:any .write scope scopes:accounting.transactions.read; accounting.contacts.read]'; then
  if test "$CHECK_ONLY" = no; then
    bao_ kv metadata put -mount=connector_keys -custom-metadata='scopes=accounting.transactions.read; accounting.contacts.read' -custom-metadata='not_requested=any .write scope' xero >/dev/null || fail "the vault would not define the credential slot for xero"
  fi
  slot_ok xero 'map[not_requested:any .write scope scopes:accounting.transactions.read; accounting.contacts.read]' || missing "the credential slot for xero"
fi

if test "$NOT_IN_FORCE" -ne 0; then
  test "$CHECK_ONLY" = yes && fail "$NOT_IN_FORCE of this release's vault changes are not in force"
  fail "$NOT_IN_FORCE of this release's vault changes did not take after being written"
fi
if test "$CHECK_ONLY" = no; then
  bao_ token renew >/dev/null 2>&1 || true
fi
say "in force: 4 engines, $POLICIES policies, the connector-run token role and 9 credential slots"
