"""The install acceptance check for Google Drive: a folder connected, indexed and read, no socket.

`brain.ops.acceptance_checks_google` proves a Google source whose values are figures. A Drive folder
is the other shape: its index is the folder's files, and what a question is answered from is a
file's words, read from Drive while the asker waits and handed to the model step as a passage. So
this check connects a folder made up for the run inside the check's transaction through the store
the Connectors screen's routes call, lets the worker's own `brain.ops.connector_sync_run.attempt`
list it into the index with a token a generated key file bought, and then asks the application's
own passage reader (`brain.ops.drive_passages.DrivePassages`) over the index it wrote.

**No socket is opened and no real key is held.** Google's token endpoint and the Drive API are one
recorded caller answering in the documented envelopes and noting what it was asked. The key file is
generated by the check, signs a real assertion that nobody receives, and is dropped with the check.
See `brain.ops.acceptance_checks_connectors.A_RECORDED_ANSWER_IS_NEVER_A_CALL`.

**The words are a canary, so being read live and being kept nowhere are one observation each.**
The Google Doc's exported text carries a word minted for the run. It is told to the reader granted
the folder's files in the folder's department, only after Drive was asked for it, and afterwards
the install's index audit finds it in no table.

**Absent and denied are compared as the person sees them.** A reader without the grant, and a
reader holding it in the other department, are each handed exactly what a question about a file
that is not there hands them, and Drive is asked nothing for either.

**The tree is walked, and a file locked narrower than its folder is never read.** The Doc sits in
a subfolder, so the worker lists the pin and then the subfolder, and the Doc is read through the
subfolder the walk kept. A second file is listed with its folder's sharing and has its inherited
permissions switched off since: a question naming it has its metadata read, and its words are
never asked for
(`brain.connectors.google_drive.A_FILE_LOCKED_NARROWER_THAN_ITS_FOLDER_IS_NEVER_READ`).

**A tree wider and deeper than one pass is read whole over two, depth first (M11.9.15).** The
second check's pin holds three subfolders, the first of them a chain as deep as a pass has pages,
so the first pass stops inside that chain with the other two waiting on the path it saves. The
next pass starts at the page the first did not ask, not at the pin, finishes the chain and then
the two that waited, and leaves no place behind; every file is in the index once
(`brain.connectors.google_drive.A_WALK_S_PLACE_IS_ITS_PATH_AND_NOT_ITS_QUEUE`).

**The check steps aside where the install has Google Drive connected.** Connecting a source that
is connected already is refused, for `A_CONNECTED_SOURCE_IS_NOT_CONNECTED_AGAIN`'s reason.

Task ids: M11.6.7, M11.9.15
"""

from __future__ import annotations

import json
import secrets
import uuid
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Final
from urllib.parse import parse_qs, urlsplit

from brain.core.scope import Scope
from brain.ops.acceptance import CheckFailedError, CheckNotRunError, check
from brain.ops.acceptance_checks_connectors import (
    A_CONNECTED_SOURCE_IS_NOT_CONNECTED_AGAIN,
    _no_wait,
    _nothing_kept,
    _Resolver,
    _search,
)
from brain.ops.acceptance_checks_google import A, B, _KeyFiles, _no_subject, a_key_file
from brain.ops.acceptance_checks_sources import _connection
from brain.ops.acceptance_run import SET_UP_REACH, Harness

if TYPE_CHECKING:
    from collections.abc import Mapping

    from brain.ops.connector_store import Connection
    from brain.ops.connector_sync_run import SourceAnswer

# ------------------------------------------------------------------ written-down reasons
#: Where this module's checks stand on the Install page, before every larger key. See
#: `brain.ops.acceptance.A_CHECK_MODULE_IS_FOUND_AND_PLACES_ITSELF`.
CHECK_ORDER: Final = 380

#: What the check says where the install has Google Drive connected already.
DRIVE_IS_CONNECTED_HERE_ALREADY: Final = (
    "this install has Google Drive connected already, so the check does not connect it again "
    "and does not read it"
)

__all__ = ["A_CONNECTED_SOURCE_IS_NOT_CONNECTED_AGAIN", "DRIVE_IS_CONNECTED_HERE_ALREADY"]

#: The types the recorded folder's files are.
FOLDER_MIME: Final = "application/vnd.google-apps.folder"
DOC_MIME: Final = "application/vnd.google-apps.document"
TEXT_MIME: Final = "text/plain"


# ------------------------------------------------------------------------ the helpers
@dataclass
class _DriveFile:
    """One file of the recorded folder, as the Drive API would describe it."""

    file_id: str
    name: str
    mime_type: str
    parent: str
    words: str = field(default="", repr=False)
    #: Listed with its folder's sharing, and locked narrower than its folder since.
    locked_since_listed: bool = False

    def listed(self, *, now: bool = False) -> dict[str, Any]:
        return {
            "id": self.file_id,
            "name": self.name,
            "mimeType": self.mime_type,
            "modifiedTime": "2019-03-02T10:00:00.000Z",
            "headRevisionId": f"rev-{self.file_id}",
            "trashed": False,
            "parents": [self.parent],
            "inheritedPermissionsDisabled": now and self.locked_since_listed,
        }


@dataclass
class _Drive:
    """Google's token endpoint and the Drive API as recorded answers. No socket.

    A service account holding Viewer is shown no file's permissions, so none is answered. Every
    metadata read and every read of a file's words is noted by the file it named.
    """

    folder_id: str
    files: tuple[_DriveFile, ...]
    tokens: list[bytes] = field(default_factory=list, repr=False)
    headers: list[dict[str, str]] = field(default_factory=list, repr=False)
    listings: int = 0
    metadata_read: list[str] = field(default_factory=list)
    words_read: list[str] = field(default_factory=list)

    def calls(self) -> int:
        """Every call a question made, read when asked rather than kept as a copy."""
        return len(self.metadata_read) + len(self.words_read)

    def get(
        self, url: str, *, address: str, headers: Mapping[str, str], max_bytes: int
    ) -> SourceAnswer:
        from brain.ops.connector_sync_run import SourceAnswer

        del address, max_bytes
        self.headers.append(dict(headers))
        parts = urlsplit(url)
        asked = parse_qs(parts.query)
        if parts.path == "/drive/v3/files":
            self.listings += 1
            folders = {self.folder_id} | {
                one.file_id for one in self.files if one.mime_type == FOLDER_MIME
            }
            folder = next(
                (
                    one
                    for one in folders
                    if asked.get("q") == [f"'{one}' in parents and trashed = false"]
                ),
                None,
            )
            if folder is None:
                return SourceAnswer(status=400, headers={}, body=b"{}")
            listed = {"files": [one.listed() for one in self.files if one.parent == folder]}
            return SourceAnswer(status=200, headers={}, body=json.dumps(listed).encode())
        for one in self.files:
            if parts.path == f"/drive/v3/files/{one.file_id}/export":
                self.words_read.append(one.file_id)
                return SourceAnswer(status=200, headers={}, body=one.words.encode())
            if parts.path == f"/drive/v3/files/{one.file_id}":
                if asked.get("alt") == ["media"]:
                    self.words_read.append(one.file_id)
                    return SourceAnswer(status=200, headers={}, body=one.words.encode())
                self.metadata_read.append(one.file_id)
                body = json.dumps(one.listed(now=True)).encode()
                return SourceAnswer(status=200, headers={}, body=body)
        return SourceAnswer(status=404, headers={}, body=b"{}")

    def post(
        self,
        url: str,
        *,
        address: str,
        headers: Mapping[str, str],
        body: bytes,
        max_bytes: int,
    ) -> SourceAnswer:
        from brain.connectors.google_token import GOOGLE_TOKEN_URL
        from brain.ops.connector_sync_run import SourceAnswer

        del address, headers, max_bytes
        if url != GOOGLE_TOKEN_URL:
            return SourceAnswer(status=404, headers={}, body=b"{}")
        self.tokens.append(body)
        issued = {"access_token": f"ya29.{secrets.token_hex(8)}", "token_type": "Bearer"}
        return SourceAnswer(status=200, headers={}, body=json.dumps(issued).encode())


# ------------------------------------------------- a connected folder's words are read live
@check(
    leaves=("M11.6.7",),
    sentence=(
        "A Google Drive folder and its subfolder, made up for the check, are connected and walked "
        "into the index by the worker with a token its key file bought. A reader granted its files "
        "in its department is told a nested Doc's words read when asked; readers without are told "
        "what a missing file tells them; a locked file is never read; no word is in any table."
    ),
)
async def a_drive_folder_s_words_are_read_live_and_kept_nowhere(h: Harness) -> None:
    from brain.connectors import google_drive
    from brain.ops.acceptance_checks_tables import _console
    from brain.ops.connector_store import StoredConnections, live
    from brain.ops.connector_sync import SyncOutcome, plan_for
    from brain.ops.connector_sync_run import attempt
    from brain.ops.connector_sync_store import LiveConnection
    from brain.ops.drive_passages import DrivePassages, indexed_files

    source = google_drive.GOOGLE_DRIVE
    if (await h.execute(live(source))).scalar_one_or_none() is not None:
        raise CheckNotRunError(DRIVE_IS_CONNECTED_HERE_ALREADY)
    await h.found_departments()

    # The folder, each file named by a word nothing else holds, the Doc's words a canary.
    folder_id = f"acceptance{secrets.token_hex(8)}"
    canary = h.word()
    kept_back = h.word()
    sub = _DriveFile(
        file_id=f"fld{secrets.token_hex(8)}",
        name=h.word(),
        mime_type=FOLDER_MIME,
        parent=folder_id,
    )
    doc = _DriveFile(
        file_id=f"doc{secrets.token_hex(8)}",
        name=h.word(),
        mime_type=DOC_MIME,
        parent=sub.file_id,
        words=f"The words of the document are {canary}.",
    )
    locked = _DriveFile(
        file_id=f"txt{secrets.token_hex(8)}",
        name=f"{h.word()}.txt",
        mime_type=TEXT_MIME,
        parent=folder_id,
        words=f"The words kept back are {kept_back}.",
        locked_since_listed=True,
    )
    drive = _Drive(folder_id=folder_id, files=(sub, doc, locked))
    keys = _KeyFiles(a_key_file())
    connection = _connection(
        h,
        source,
        {
            google_drive.FOLDER_SETTING: folder_id,
            google_drive.DOMAIN_SETTING: f"{h.word().lower()}.example",
            google_drive.DEPARTMENT_SETTING: A,
            google_drive.STEWARD_SETTING: h.principal(A, "steward"),
        },
    )

    # Connected as the Connectors screen's route connects it, and listed as the worker lists it.
    await StoredConnections(h.sessions).connect(
        connector=connection.connector,
        settings=connection.settings,
        digest=connection.digest,
        actor=h.actor,
        trace_id=h.trace_id,
        ent_hash=SET_UP_REACH,
        keep_key=_nothing_kept,
    )
    plan = plan_for(connection, last=None, now=h.now)
    if plan.refused or not plan.due:
        raise CheckFailedError("the worker's plan would not read a folder connected as declared")
    done = await attempt(
        LiveConnection(id=uuid.uuid4(), connection=connection),
        plan,
        previous=None,
        sessions=h.sessions,
        keys=keys,
        caller=drive,
        resolver=_Resolver(),
        clock=lambda: h.now,
        sleep=_no_wait,
        poster=drive,
    )
    if done.outcome is not SyncOutcome.SYNCED or done.records != len(drive.files):
        raise CheckFailedError("the worker did not keep the folder's files in the index")
    if drive.listings != 2:
        raise CheckFailedError("the worker did not walk the folder and its subfolder once each")
    if len(drive.tokens) != 1 or not _no_subject(drive.tokens[0]) or drive.calls():
        raise CheckFailedError("the worker's listing was not one token for the account")
    if any("PRIVATE KEY" in json.dumps(one) for one in drive.headers):
        raise CheckFailedError("a header carried the key file")

    # The application's own passage reader, over the index the worker wrote in this transaction.
    async def connected() -> Connection | None:
        return connection

    async def indexed() -> Any:
        return await indexed_files(h.sessions)

    passages = DrivePassages(
        connected,
        indexed,
        keys=keys,
        caller=drive,
        poster=drive,
        resolver=_Resolver(),
        clock=lambda: h.now,
    )

    async def asked(principal_id: str, name: str) -> tuple[str, ...]:
        reach = await _console(h, principal_id, second_factor=False)
        found = await passages.passages(f"What does {name} say?", entitlement=reach, now=h.now)
        return tuple(one.document for one in found.records)

    granted, without = h.principal(A, "reader"), h.principal(A, "sales")
    elsewhere = h.principal(B, "reader")
    reads = ((f"read:{google_drive.FILE}", Scope.department(A)),)
    await h.person(granted, department=A, grants=reads)
    await h.person(without, department=A)
    await h.person(
        elsewhere,
        department=B,
        grants=((f"read:{google_drive.FILE}", Scope.department(B)),),
    )

    # Readers without the folder's files are handed what a file that is not there hands them.
    for reader in (without, elsewhere):
        refused = await asked(reader, doc.name)
        nothing = await asked(reader, h.word())
        if any(canary in one for one in refused):
            raise CheckFailedError("a file's words were told to a reader not granted them")
        if refused != nothing or drive.calls():
            raise CheckFailedError("a file a reader may not see was told apart from none")

    # The Doc's words, read from Drive when they were asked, for the reader granted them.
    told = await asked(granted, doc.name)
    if not any(canary in one for one in told) or drive.words_read != [doc.file_id]:
        raise CheckFailedError("a file's words were not read for a reader granted them")

    # The locked file is looked at and never read.
    held = await asked(granted, locked.name)
    if held or locked.file_id not in drive.metadata_read or locked.file_id in drive.words_read:
        raise CheckFailedError("a file locked narrower than its folder was read")

    # Nothing either read returned was kept anywhere.
    if await _search(h, canary) or await _search(h, kept_back):
        raise CheckFailedError("a file's words read live were found in a table")


# ------------------------------------------- a wide tree read whole over two passes (M11.9.15)
@check(
    leaves=("M11.9.15",),
    sentence=(
        "A Google Drive folder made up for the check holds three subfolders, the first a chain as "
        "deep as one pass has pages. The worker's first pass stops inside the chain and says so; "
        "the next starts where it stopped, not at the pin, then lists the two that waited, and "
        "leaves no place behind; every file is in the index once."
    ),
)
async def a_drive_tree_wider_than_a_pass_is_read_whole_depth_first(h: Harness) -> None:
    from sqlalchemy import func, select

    from brain.connectors import google_drive
    from brain.ops.acceptance_checks_change_signals import _connected, _read, _state, _Walked
    from brain.ops.connector_sync import (
        MAX_PAGES_PER_ENTITY,
        READ_BUT_CUT_SHORT,
        READ_TO_THE_END,
        SyncOutcome,
    )
    from brain.tables.projection import ProjectedRecordRow

    await h.found_departments()
    pin = f"acceptance{secrets.token_hex(8)}"
    chain = [f"fld{secrets.token_hex(8)}" for _ in range(MAX_PAGES_PER_ENTITY)]
    waiting = [f"fld{secrets.token_hex(8)}" for _ in range(2)]
    parents = [pin, *chain[:-1]]
    folders = (
        *(
            _DriveFile(file_id=one, name=h.word(), mime_type=FOLDER_MIME, parent=parent)
            for one, parent in zip(chain, parents, strict=True)
        ),
        *(
            _DriveFile(file_id=one, name=h.word(), mime_type=FOLDER_MIME, parent=pin)
            for one in waiting
        ),
    )
    files = tuple(
        _DriveFile(
            file_id=f"txt{secrets.token_hex(8)}",
            name=f"{h.word()}.txt",
            mime_type=TEXT_MIME,
            parent=folder,
        )
        for folder in (pin, *chain, *waiting)
    )
    connected = await _connected(
        h,
        google_drive.GOOGLE_DRIVE,
        {
            google_drive.FOLDER_SETTING: pin,
            google_drive.DOMAIN_SETTING: f"{h.word().lower()}.example",
            google_drive.DEPARTMENT_SETTING: A,
            google_drive.STEWARD_SETTING: h.principal(A, "steward"),
        },
    )
    keys = _KeyFiles(a_key_file())

    first_drive = _Walked(_Drive(folder_id=pin, files=(*folders, *files)))
    first = await _read(h, connected, first_drive, keys=keys, poster=first_drive)
    if first.outcome is not SyncOutcome.SYNCED or first.detail != READ_BUT_CUT_SHORT:
        raise CheckFailedError("a pass stopped at its page bound did not say it was cut short")
    if first_drive.folders != [pin, *chain[: MAX_PAGES_PER_ENTITY - 1]]:
        raise CheckFailedError("a pass did not walk the first subfolder down before the others")

    second_drive = _Walked(_Drive(folder_id=pin, files=(*folders, *files)))
    second = await _read(h, connected, second_drive, keys=keys, poster=second_drive)
    if second_drive.folders != [chain[-1], *waiting]:
        raise CheckFailedError(
            "the next pass did not start where the first stopped and list the folders it left "
            "waiting"
        )
    if second.outcome is not SyncOutcome.SYNCED or second.detail != READ_TO_THE_END:
        raise CheckFailedError("the pass that carried on was not read to the end")
    state = await _state(h, connected)
    if state is None or state.read_state is None or state.read_state.walking is not None:
        raise CheckFailedError("a walk read to its end left a place for the next pass")
    ids = [one.file_id for one in (*folders, *files)]
    held = (
        await h.execute(
            select(ProjectedRecordRow.source_id, func.count())
            .where(
                ProjectedRecordRow.source == google_drive.GOOGLE_DRIVE,
                ProjectedRecordRow.source_id.in_(ids),
                ProjectedRecordRow.deleted_at.is_(None),
            )
            .group_by(ProjectedRecordRow.source_id)
        )
    ).all()
    if sorted(str(one) for one, _ in held) != sorted(ids) or any(n != 1 for _, n in held):
        raise CheckFailedError("a tree read over two passes did not leave every file once")
