"""The install acceptance checks for the Google sources: connected, indexed and asked, no socket.

`brain.ops.acceptance_checks_sources` proves that a connected source answers on Ask for the sources
whose key is sent as it is. A Google source is the case that proof does not reach: its key is a
service account's key file, which is never sent, and its values are figures read by a report
rather than a record read again. So this check connects a property made up for the run inside the
check's transaction through the store the Connectors screen's routes call, lets the worker's own
`brain.ops.connector_sync_run.attempt` read its name with a token the key file bought, and asks
about it through the answer lane with everything the answer route hands it built by the route's
own functions, over a live reader over the same connection.

**No socket is opened and no real key is held.** Google's token endpoint, Admin API and Data API
are one recorded caller that answers in each API's documented envelope and notes what it was sent.
The key file is generated by the check, signs a real assertion that nobody receives, and is dropped
with the check. See `brain.ops.acceptance_checks_connectors.A_RECORDED_ANSWER_IS_NEVER_A_CALL`.

**The figure is a canary, so being read live and being kept nowhere are one observation each.**
The recorded report carries a number minted for the run as the property's sessions over the last
28 days. It is told to the reader granted it, only after the report was asked for at question
time, and afterwards the install's index audit finds it in no table.

**Absent and denied are compared as the person sees them.** A reader without the property, and a
reader holding the property's capability in another department, are each told exactly what a
reader asking about a property that does not exist is told. That is also what an agent whose
ceiling does not bind the property is told: its reach is its caller's narrowed, and a reach without
the grant is the same object whoever holds it.

**The check steps aside where the install has Google Analytics connected.** Connecting a source
that is connected already is refused, for `A_CONNECTED_SOURCE_IS_NOT_CONNECTED_AGAIN`'s reason.

Task ids: M11.7.1
"""

from __future__ import annotations

import json
import secrets
import uuid
from dataclasses import dataclass, field
from types import SimpleNamespace
from typing import TYPE_CHECKING, Any, Final, cast

from brain.core.scope import Scope
from brain.ops.acceptance import RESERVED_DEPARTMENTS, CheckFailedError, CheckNotRunError, check
from brain.ops.acceptance_checks_connectors import (
    A_CONNECTED_SOURCE_IS_NOT_CONNECTED_AGAIN,
    _no_wait,
    _nothing_kept,
    _Resolver,
    _search,
)
from brain.ops.acceptance_checks_sources import _connection
from brain.ops.acceptance_run import SET_UP_REACH, Harness

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable, Mapping
    from datetime import datetime

    from brain.core.entitlement import EntitlementSet
    from brain.core.envelope import TypedResult
    from brain.gate.answer import Answered
    from brain.knowledge.rows import RowRecord
    from brain.ops.connector_lease import LeaseOutcome
    from brain.ops.connector_sync_run import SourceAnswer
    from brain.ops.secrets import SecretRef

A, B = RESERVED_DEPARTMENTS

# ------------------------------------------------------------------ written-down reasons
#: Where this module's checks stand on the Install page, before every larger key. See
#: `brain.ops.acceptance.A_CHECK_MODULE_IS_FOUND_AND_PLACES_ITSELF`.
CHECK_ORDER: Final = 330

#: What the check says where the install has Google Analytics connected already.
ANALYTICS_IS_CONNECTED_HERE_ALREADY: Final = (
    "this install has Google Analytics connected already, so the check does not connect it again "
    "and does not ask about it"
)

__all__ = ["ANALYTICS_IS_CONNECTED_HERE_ALREADY", "A_CONNECTED_SOURCE_IS_NOT_CONNECTED_AGAIN"]

# ------------------------------------------------------------------------ the figures
#: The range and figure the check asks for, as a question names them.
ASKED_FIGURE: Final = "sessions_last_28_days"

#: The figure the check asks its figure tool for, over the period it names.
RANGE_FIGURE: Final = "sessions"
TOOL_PERIOD: Final = "last month"


# ------------------------------------------------------------------------ the helpers
@dataclass
class _KeyFileLease:
    """`KeyLease` over a key file the check generated."""

    given: str = field(repr=False)

    def key(self) -> str:
        return self.given

    def close(self, now: datetime) -> LeaseOutcome:
        from brain.ops.connector_lease import LeaseOutcome

        del now
        return LeaseOutcome.NONE


@dataclass
class _KeyFiles:
    """`ConnectorKeys` leasing the check's key file, noting how often it was borrowed."""

    given: str = field(repr=False)
    leased: int = 0

    def lease(self, ref: SecretRef, *, now: datetime) -> _KeyFileLease:
        del ref, now
        self.leased += 1
        return _KeyFileLease(self.given)


def a_key_file() -> str:
    """A service account key file in the shape Google Cloud downloads, with a key made here."""
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    return json.dumps(
        {
            "type": "service_account",
            "client_email": f"acceptance-{secrets.token_hex(4)}@acceptance.iam.gserviceaccount.com",
            "private_key": key.private_bytes(
                serialization.Encoding.PEM,
                serialization.PrivateFormat.PKCS8,
                serialization.NoEncryption(),
            ).decode("ascii"),
        }
    )


@dataclass
class _Google:
    """Google's token endpoint, Admin API and Data API as recorded answers. No socket.

    Every post is noted, so the check can say what was asked for and when; a report is answered
    with the check's figures and nothing else is.
    """

    property_id: str
    display_name: str
    figures: Mapping[str, str]
    reports: int = 0
    ranges: list[tuple[str, str]] = field(default_factory=list)
    tokens: list[bytes] = field(default_factory=list, repr=False)
    headers: list[dict[str, str]] = field(default_factory=list, repr=False)

    def get(
        self, url: str, *, address: str, headers: Mapping[str, str], max_bytes: int
    ) -> SourceAnswer:
        from brain.ops.connector_sync_run import SourceAnswer

        del address, max_bytes
        self.headers.append(dict(headers))
        if url.endswith(f"/v1beta/properties/{self.property_id}"):
            body = {
                "name": f"properties/{self.property_id}",
                "displayName": self.display_name,
                "createTime": "2019-03-01T10:00:00.000Z",
                "updateTime": "2019-03-02T10:00:00.000Z",
                "timeZone": "Etc/UTC",
            }
            return SourceAnswer(status=200, headers={}, body=json.dumps(body).encode())
        return SourceAnswer(status=404, headers={}, body=b"{}")

    def post(
        self,
        url: str,
        *,
        address: str,
        headers: Mapping[str, str],
        body: bytes,
        max_bytes: int,
    ) -> SourceAnswer:
        from brain.connectors.google_token import GOOGLE_TOKEN_URL
        from brain.ops.connector_sync_run import SourceAnswer

        del address, max_bytes
        if url == GOOGLE_TOKEN_URL:
            self.tokens.append(body)
            issued = {"access_token": f"ya29.{secrets.token_hex(8)}", "token_type": "Bearer"}
            return SourceAnswer(status=200, headers={}, body=json.dumps(issued).encode())
        self.headers.append(dict(headers))
        if url.endswith(f"/v1beta/properties/{self.property_id}:runReport"):
            self.reports += 1
            ranges = json.loads(body)["dateRanges"]
            answered = self._report() if len(ranges) > 1 else self._one_range(ranges[0])
            return SourceAnswer(status=200, headers={}, body=json.dumps(answered).encode())
        return SourceAnswer(status=404, headers={}, body=b"{}")

    def _one_range(self, asked: Mapping[str, str]) -> dict[str, Any]:
        """A figure tool's one range, its sessions the check's figure for the days asked."""
        from brain.connectors.google_analytics import FIGURES

        self.ranges.append((asked["startDate"], asked["endDate"]))
        figure = self.figures.get(RANGE_FIGURE, "0")
        return {
            "metricHeaders": [{"name": name} for name in FIGURES],
            "rows": [{"metricValues": [{"value": figure}, {"value": "0"}, {"value": "0"}]}],
        }

    def reports_asked(self) -> int:
        """How many reports were asked for so far. A method so the count is read when asked."""
        return self.reports

    def _report(self) -> dict[str, Any]:
        from brain.connectors.google_analytics import FIGURES, RANGES

        return {
            "dimensionHeaders": [{"name": "dateRange"}],
            "metricHeaders": [{"name": name} for name in FIGURES],
            "rows": [
                {
                    "dimensionValues": [{"value": one.name}],
                    "metricValues": [
                        {"value": self.figures.get(f"{label}_{one.name}", "0")}
                        for label in FIGURES.values()
                    ],
                }
                for one in RANGES
            ],
        }


def google_analytics_tool() -> str:
    """The figure tool's name, as `brain.knowledge.connector_figures` registers it."""
    from brain.connectors.google_analytics import GOOGLE_ANALYTICS
    from brain.knowledge.connector_figures import FIGURE_TOOL_NAMES

    return FIGURE_TOOL_NAMES[GOOGLE_ANALYTICS]


def _prose(answered: Answered) -> str:
    """What the person was told, read from the frames as the web draws them."""
    from brain.ops.acceptance_checks_chat import heard

    return heard(answered.frames).prose


def _no_subject(form: bytes) -> bool:
    """Whether the assertion in a token request names no person, which is the account reading as
    itself. See `google_token.A_CONNECTED_GOOGLE_SOURCE_READS_AS_ITS_SERVICE_ACCOUNT`."""
    import base64
    from urllib.parse import parse_qs

    assertion = parse_qs(form.decode("ascii"))["assertion"][0]
    claims = assertion.split(".")[1]
    decoded = json.loads(base64.urlsafe_b64decode(claims + "=" * (-len(claims) % 4)))
    return isinstance(decoded, dict) and "sub" not in decoded and "scope" in decoded


# ------------------------------------------------ 1. a connected property answers its figures
@check(
    leaves=("M11.7.1",),
    sentence=(
        "A Google Analytics property made up for the check is connected and its name read by the "
        "worker with a token its key file bought. On Ask, and through its figure tool for last "
        "month, readers without the property get what a missing property gets, the granted reader "
        "gets sessions read from a report when asked, and no figure is in any table."
    ),
)
async def an_analytics_property_answers_its_figures_live_and_keeps_none(
    h: Harness,
) -> None:
    from brain.api_routes import (
        connected_questions_of,
        covered_at,
        field_policies,
        row_readers,
        source_field_policies,
    )
    from brain.connectors import google_analytics
    from brain.gate.answer import answer_lane
    from brain.gate.context import Channel
    from brain.gate.finish import Origin
    from brain.identity.principal_store import StoredPrincipals
    from brain.knowledge.classified_rows import QUESTION_SHAPES, label_of
    from brain.knowledge.row_store import SessionRowSource
    from brain.ops.acceptance_checks_tables import _console
    from brain.ops.connector_store import StoredConnections, live
    from brain.ops.connector_sync import SyncOutcome, plan_for
    from brain.ops.connector_sync_run import attempt
    from brain.ops.connector_sync_store import LiveConnection
    from brain.ops.live_read_run import ConnectedSources
    from brain.ops.live_records import SourceRecords
    from brain.ops.trace_sink import CountingTraceSink
    from brain.tools.startup import build_registry

    source, entity = google_analytics.GOOGLE_ANALYTICS, google_analytics.ENTITY_PROPERTY
    if (await h.execute(live(source))).scalar_one_or_none() is not None:
        raise CheckNotRunError(ANALYTICS_IS_CONNECTED_HERE_ALREADY)
    await h.found_departments()

    # The property, its name a word nothing else holds, and its figure a number minted for the run.
    property_id = str(10**8 + secrets.randbelow(9 * 10**8))
    name = h.word()
    canary = str(10**14 + secrets.randbelow(9 * 10**14))
    ranged = str(10**14 + secrets.randbelow(9 * 10**14))
    google = _Google(
        property_id=property_id,
        display_name=name,
        figures={ASKED_FIGURE: canary, RANGE_FIGURE: ranged},
    )
    keys = _KeyFiles(a_key_file())
    connection = _connection(
        h,
        source,
        {
            google_analytics.PROPERTY_SETTING: property_id,
            google_analytics.DEPARTMENT_SETTING: A,
        },
    )

    # Connected as the Connectors screen's route connects it, and read as the worker reads it.
    await StoredConnections(h.sessions).connect(
        connector=connection.connector,
        settings=connection.settings,
        digest=connection.digest,
        actor=h.actor,
        trace_id=h.trace_id,
        ent_hash=SET_UP_REACH,
        keep_key=_nothing_kept,
    )
    plan = plan_for(connection, last=None, now=h.now)
    if plan.refused or not plan.due:
        raise CheckFailedError("the worker's plan would not read a property connected as declared")
    done = await attempt(
        LiveConnection(id=uuid.uuid4(), connection=connection),
        plan,
        previous=None,
        sessions=h.sessions,
        keys=keys,
        caller=google,
        resolver=_Resolver(),
        clock=lambda: h.now,
        sleep=_no_wait,
        poster=google,
    )
    if done.outcome is not SyncOutcome.SYNCED or done.records != 1:
        raise CheckFailedError("the worker did not keep the connected property from its answers")
    if len(google.tokens) != 1 or not _no_subject(google.tokens[0]) or google.reports_asked():
        raise CheckFailedError("the worker's read was not one token for the account and no report")
    if any("PRIVATE KEY" in json.dumps(one) for one in google.headers):
        raise CheckFailedError("a header carried the key file")

    # What the answer route builds, by its own functions, over the check's transaction.
    state = SimpleNamespace(db_sessions=h.sessions)
    rules = [one for one in await connected_questions_of(state) if one.source == source]
    if not rules:
        raise CheckFailedError("the connected property contributed no question shapes to Ask")
    registry = build_registry(source=h.settings.tool_source, records=SessionRowSource(h.sessions))
    readers = row_readers(registry)
    if (source, entity) not in readers:
        raise CheckFailedError("the application registered no reader for the connected property")

    async def connected() -> Any:
        return ConnectedSources(
            {source: connection},
            keys=keys,
            caller=google,
            resolver=_Resolver(),
            clock=lambda: h.now,
            poster=google,
        )

    live_records = SourceRecords(connected=connected, clock=lambda: h.now)

    async def ask(principal_id: str, question: str) -> Answered:
        person = await StoredPrincipals(h.sessions).live_principal(principal_id)
        if person is None:
            raise CheckFailedError("a reserved person was not live in the directory")
        reach: EntitlementSet = await _console(h, principal_id, second_factor=False)
        return await answer_lane(
            question,
            origin=Origin(trace_id=h.trace_id, principal=person, channel=Channel.CONSOLE),
            recorders=(),
            rules=rules,
            readers=readers,
            entitlement=reach,
            policies=field_policies(registry),
            reachable_sources=covered_at(registry, reach, h.now),
            sink=CountingTraceSink(),
            now=h.now,
            clock=lambda: h.now,
            live=live_records,
            source_policies=source_field_policies(registry),
        )

    def asking(named: str) -> str:
        return QUESTION_SHAPES[0].format(label=label_of(ASKED_FIGURE), slot=named)

    reads = (f"read:{entity}", f"read:{entity}.display_name", f"read:{entity}.{ASKED_FIGURE}")
    granted, without = h.principal(A, "analyst"), h.principal(A, "sales")
    elsewhere = h.principal(B, "analyst")
    await h.person(granted, department=A, grants=tuple((one, Scope.department(A)) for one in reads))
    await h.person(without, department=A)
    await h.person(
        elsewhere, department=B, grants=tuple((one, Scope.department(B)) for one in reads)
    )

    # Readers without the property are told what a property that is not there is told.
    for reader in (without, elsewhere):
        refused = await ask(reader, asking(name))
        nobody = await ask(reader, asking(h.word()))
        if refused.composed is not None or canary in _prose(refused):
            raise CheckFailedError("a property's figure was told to a reader not granted it")
        if _prose(refused) != _prose(nobody):
            raise CheckFailedError("a property a reader may not see was told apart from none")

    # The figure, read from the report when it was asked, for the reader granted it.
    told = await ask(granted, asking(name))
    if told.composed is None or canary not in _prose(told):
        raise CheckFailedError("a connected property's figure was not told to a reader granted it")
    if google.reports_asked() != 1:
        raise CheckFailedError("the figure was not read from Google when it was asked")

    # The figure tool, as a workflow's step calls it: last month, read live, at the caller's reach.
    from brain.connectors.date_range import RangeRequest, window_of

    tools = build_registry(
        source=h.settings.tool_source, records=SessionRowSource(h.sessions), figures=live_records
    )
    # A cast at the registry's boundary, for `brain.api_routes.passage_search_for`'s reason: the
    # registry holds handlers of more than one shape, and the name selects the one this is.
    tool = cast(
        "Callable[..., Awaitable[TypedResult[RowRecord]]]",
        tools.get(google_analytics_tool()).handler,
    )
    for reader in (without, elsewhere):
        reach = await _console(h, reader, second_factor=False)
        found = await tool(RangeRequest(period=TOOL_PERIOD), entitlement=reach, now=h.now)
        if found.records:
            raise CheckFailedError("the figure tool read a property for a reader not granted it")
    reach = await _console(h, granted, second_factor=False)
    found = await tool(RangeRequest(period=TOOL_PERIOD), entitlement=reach, now=h.now)
    period = window_of(TOOL_PERIOD, today=h.now.date())
    if google.ranges != [(period.start.isoformat(), period.end.isoformat())]:
        raise CheckFailedError("the figure tool did not ask Google for the range it was given")
    if [one.model_dump().get(RANGE_FIGURE) for one in found.records] != [ranged]:
        raise CheckFailedError("the figure tool did not hand back the range's figure")

    # Nothing either report returned was kept anywhere.
    if await _search(h, canary) or await _search(h, ranged):
        raise CheckFailedError("a figure read live was found in a table")
