"""The work in the plan that no commit can close, and the document that lists it.

About thirty of the leaves left in the work breakdown are not code. They are things a person
does on the week of a migration, to one client, on one day: announce the switch before removing
the outgoing bot, revoke every OAuth grant, record the date access actually ended, agree twenty
real questions as the acceptance set, run a backup drill in front of the client. Every one of
them has to happen and not one of them is a commit.

**They were being counted as if they were commits, and that is what this module is for.** The
percentage on the build page is the number somebody reads to know how the build is going, and
mixing two kinds of work into one denominator makes it stop rising at around 86 percent for a
reason that is not the build stalling. The flags live in `docs/wbs/acts.js`, keyed by leaf id,
and this module is the reader: buildable done and acts outstanding become two numbers instead
of one.

**Generated, never written, and that is the whole argument for the document.** A delivery
checklist somebody types is a checklist that goes short: it is written once at the start of a
migration, a leaf is added to the plan in week two, and nothing anywhere notices that the list
and the plan now disagree. `docs/delivery-checklist.md` is produced from the flags and a test
asserts the file on disk is what the generator produces, so a flagged leaf missing from it is
a red suite rather than a paragraph nobody re-reads. See
`A_CHECKLIST_SOMEBODY_TYPES_IS_A_CHECKLIST_THAT_GOES_SHORT`.

**A list nothing gates is a list nobody reads, so five of them gate the cutover.** That
objection was raised against moving this work out of the plan and it was right, and it is
answered here rather than by dropping the idea: the leaves whose absence has a security
consequence are named in `CUTOVER_GATED_ACTS` and `brain.migration.decommission` refuses to
report a completed cutover while any of them is unrecorded. It gates the day, not the build.
See `A_LIST_NOTHING_GATES_IS_A_LIST_NOBODY_READS`.

**The gated ids are written here and not read out of the work breakdown at the moment the gate
runs**, which looks like duplication and is the opposite. A required list loaded from a
document has one failure mode and it is the wrong one: the document is missing, or it is an
older copy, or it was regenerated by somebody who had unflagged a leaf, and the gate then finds
nothing required and passes. A gate that passes because its own list was absent is worse than
no gate, because the screen goes green. So the ids are a constant, and a test asserts that the
constant is exactly the set the work breakdown flags, which is the comparison against something
outside itself that `CLAUDE.md` asks for. See
`A_GATE_WHOSE_LIST_LIVES_IN_A_DOCUMENT_PASSES_WHEN_THE_DOCUMENT_IS_ABSENT`.

**Four of the flagged leaves cannot be code here whoever writes them.** They name one company's
own things: how many house skills there are, four of them by name, which chat groups each agent
sits in, and what the outgoing vendor produced that people still rely on. The first rule in
`CLAUDE.md` is that no company's details go into this repository, so those four are recorded as
unbuildable here rather than left looking merely undone, and the checklist says so beside each
one. Nothing in this module holds the answers, only the fact that a person supplies them.

What was rejected. Moving the thirty out of the work breakdown entirely, which is the cleanest
tracker and loses the only record that they are in scope at all. Flagging them inside the leaf,
which means changing the shape of 1251 leaves to mark 33 and is how a group gets inserted by
accident into a numbering where the id is the position. And folding the gated acts into
`decommission_gaps`, which reads as the tidier design and answers a different question: that
function reports what is still true of the old system, and two of the gated acts are about the
client's tenant and the client's backup rather than about the old system at all.

Task ids: none
"""

from __future__ import annotations

import enum
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any, Final

from brain.migration.inventory import MigrationError


class ChecklistError(MigrationError):
    """Raised when the flags and the work breakdown disagree about what a leaf is."""


# ------------------------------------------------------------------ written-down reasons
#: Why the document is generated rather than kept.
A_CHECKLIST_SOMEBODY_TYPES_IS_A_CHECKLIST_THAT_GOES_SHORT: Final = (
    "A delivery checklist written by hand is written once, at the point somebody has the "
    "whole migration in their head, and it is never the thing that gets updated when the "
    "plan changes. It cannot report that it is out of date, because a list is complete by "
    "looking complete. Generating it from the flags means a leaf added to the plan appears "
    "on the list, a leaf dropped from the list fails the suite, and neither of those is "
    "somebody remembering."
)

#: Why the security subset gates something rather than only appearing.
A_LIST_NOTHING_GATES_IS_A_LIST_NOBODY_READS: Final = (
    "Separating this work from the build makes the percentage mean one thing and makes the "
    "work easier to lose, and these are the leaves with a security consequence: an OAuth "
    "grant nobody withdrew is how an outgoing vendor keeps reading a client's mail after "
    "everybody believes the account is closed. So the subset gates the cutover. It gates the "
    "day rather than the build, because refusing a commit for an act that cannot happen yet "
    "would stop the build for a reason the build cannot fix."
)

#: Why the gated ids are a constant here rather than a query against the work breakdown.
A_GATE_WHOSE_LIST_LIVES_IN_A_DOCUMENT_PASSES_WHEN_THE_DOCUMENT_IS_ABSENT: Final = (
    "A gate that loads what it requires from a file has a state where the file is missing, "
    "stale or regenerated with a leaf unflagged, and in every one of them it finds nothing "
    "required and reports a clean cutover. The failure is silent and it is in the permissive "
    "direction, which is the one that gets shipped. The ids are therefore a constant, and a "
    "test compares that constant against the flags rather than against itself."
)

#: Why a leaf a commit cannot close is not the same as a leaf nobody has started.
A_LEAF_NO_COMMIT_CAN_CLOSE_IS_NOT_A_LEAF_NOBODY_HAS_STARTED: Final = (
    "Undone and unbuildable look identical on a tracker and mean opposite things. Undone is "
    "somebody's next afternoon. Unbuildable here means no afternoon by anybody in this "
    "repository will close it, either because it happens on a day with a client in the room "
    "or because it names one company's own things and a product every client installs cannot "
    "hold them. Recording which is which is what stops the next reader spending a day trying "
    "to make one fit."
)


class ActKind(enum.StrEnum):
    """Why a leaf cannot be closed by a commit."""

    #: A person does it on the week of the migration.
    ACT = "ACT"
    #: A person does it, and it could not have been code here whoever wrote it.
    UNBUILDABLE = "UNBUILDABLE"


# --------------------------------------------------------------- the acts, read from the plan
@dataclass(frozen=True)
class Act:
    """One leaf of the work breakdown that a person does rather than a commit."""

    leaf: str
    text: str
    kind: ActKind
    gates_cutover: bool
    #: Why it is unbuildable, or why it gates. Empty for a plain act, whose sentence is all
    #: there is to say about it.
    why: str

    def __post_init__(self) -> None:
        if not self.leaf.strip():
            msg = "an act names no leaf, so nothing on the checklist can be found in the plan"
            raise ChecklistError(msg)
        if not self.text.strip():
            msg = f"{self.leaf} is flagged as an act and the plan has no sentence for it"
            raise ChecklistError(msg)


#: The acts whose absence has a security consequence, and what has to be true of each.
#:
#: The sentences are written here rather than taken from the leaf, because the leaf names a
#: vendor and a client's own estate and nothing under `src` may. They are also what the refusal
#: says, and a refusal that quotes a plan is a refusal that stops making sense on the day the
#: plan is edited.
#:
#: Four were named in the decision and the fifth is argued: removing the outgoing application
#: from the tenant is the authorisation half of removing its bot from the groups, and either
#: one left undone leaves the outgoing vendor receiving the client's messages.
#:
#: What is deliberately not here, because the reason for an omission is harder to reconstruct
#: later than the reason for an inclusion. The security review and the penetration test are
#: written "if the client requires one" and "where contractually required", and a gate on a
#: conditional act refuses every cutover for every client who does not require it, which is a
#: gate somebody switches off, taking the five real ones with it. The export before the account
#: closes loses data rather than leaving access open, and whether the copy can be read back is
#: already gated through the drill.
CUTOVER_GATED_ACTS: Final[Mapping[str, str]] = MappingProxyType(
    {
        "M37.2.5.4": (
            "the outgoing system's bot has been removed from every group it was installed "
            "in, because a bot still in a group is still receiving that group's messages"
        ),
        "M37.2.6.1": (
            "every OAuth grant the outgoing system holds has been withdrawn and the "
            "withdrawal confirmed, because cancelling a subscription does not withdraw one"
        ),
        "M37.2.6.2": (
            "the outgoing system's application has been removed from the tenant and not "
            "only from its groups, because the tenant installation is where its scopes live"
        ),
        "M37.2.6.5": (
            "the date the outgoing system's access actually ended has been recorded, which "
            "is a different date from the last invoice and cannot be reconstructed later"
        ),
        "M37.4.1.3": (
            "a backup has been read back in front of the client, so what is retained is a "
            "copy somebody has opened rather than a file"
        ),
    }
)


def _wbs_path(repo: Path) -> Path:
    return repo / "docs" / "wbs.json"


def load_acts(wbs_path: Path) -> tuple[Act, ...]:
    """Every flagged leaf in the work breakdown, in plan order.

    Refuses a flag whose id is not a leaf. That is the failure this whole arrangement is
    exposed to: leaf ids are positional, so inserting a group above a flagged leaf repoints
    the flag at different work without changing a character of it. `docs/wbs/acts.js` carries
    the sentence each flag was written against and both generators refuse to run when one no
    longer matches, so by the time the export is read here the fingerprints have been checked.
    This is the second half of that, and it catches the case the generators cannot: a
    `wbs.json` edited by hand or left behind by a failed export.
    """
    from brain.status import leaf_sentences, load_wbs

    wbs = load_wbs(wbs_path)
    # The one reader of the leaf sentences, which already refuses a module whose sentences and
    # ids have drifted out of alignment. A second zip here would be a second place that rule
    # is applied, and the wrong copy is the one that ships.
    texts = leaf_sentences(wbs_path)
    found: list[Act] = []
    for module in wbs.get("modules", []):
        flags: Mapping[str, Any] = module.get("leaf_acts", {})
        if not flags:
            continue
        for leaf in module.get("leaf_ids", []):
            flag = flags.get(leaf)
            if flag is None:
                continue
            found.append(
                Act(
                    leaf=leaf,
                    text=texts.get(leaf, ""),
                    kind=ActKind(flag["kind"]),
                    gates_cutover=bool(flag.get("gate")),
                    why=str(flag.get("why", "")),
                )
            )
        unknown = sorted(set(flags) - set(module.get("leaf_ids", [])))
        if unknown:
            msg = (
                f"{module['id']}: {', '.join(unknown)} flagged as acts and named by no leaf, "
                "so a flag points at a group or at a leaf that has moved"
            )
            raise ChecklistError(msg)
    return tuple(found)


def act_group_names(wbs_path: Path) -> dict[str, str]:
    """The heading over each flagged leaf, by group id, so the checklist reads on its own."""
    from brain.status import load_wbs

    names: dict[str, str] = {}
    for module in load_wbs(wbs_path).get("modules", []):
        names[module["id"]] = module["name"]
        names.update(module.get("act_groups", {}))
    return names


def gated_acts(acts: tuple[Act, ...]) -> tuple[str, ...]:
    """The leaf ids the work breakdown flags as gating the cutover, sorted."""
    return tuple(sorted(one.leaf for one in acts if one.gates_cutover))


# ------------------------------------------------------------------------ the document itself
#: The first line of the generated file, so a reader who opens it to edit it is told not to.
GENERATED_BY: Final = (
    "<!-- Generated from docs/wbs/acts.js by brain.migration.checklist. Do not edit: run "
    "`uv run python -m brain.migration.checklist` instead. -->"
)


def _heading(level: int, text: str) -> str:
    return f"{'#' * level} {text}"


def checklist_markdown(wbs_path: Path) -> str:
    """The delivery checklist, built from the flags and from nothing else.

    Deterministic and dateless. A generated document carrying the moment it was generated
    dirties the working tree on every run, so the check that it is up to date becomes a check
    that somebody ran it most recently, which is not the same question.
    """
    acts = load_acts(wbs_path)
    names = act_group_names(wbs_path)
    gated = gated_acts(acts)

    lines: list[str] = [
        GENERATED_BY,
        "",
        "# Delivery checklist",
        "",
        "Work in the plan that no commit can close. Every item here is done by a person, on "
        "the week of a migration, with a client. They are counted separately from the build "
        "for that reason: the percentage on the build page measures work that closes by being "
        "written, and these do not.",
        "",
        f"{len(acts)} items, {len(gated)} of which gate the cutover.",
        "",
        "**The items marked GATES CUTOVER are refused rather than listed.** "
        "`brain.migration.decommission` will not report a completed cutover while any of them "
        "is unrecorded, because their absence has a security consequence and a list nothing "
        "gates is a list nobody reads.",
        "",
        "**The items marked NOT CODE HERE could not be built by anybody in this repository.** "
        "They name one company's own things, and the first rule of this repository is that no "
        "company's details go into it. They are recorded rather than left looking undone, so "
        "nobody spends a day trying to make them fit.",
        "",
    ]

    seen_groups: set[str] = set()
    for act in acts:
        parts = act.leaf.split(".")
        for cut in range(1, len(parts)):
            group = ".".join(parts[:cut])
            if group in seen_groups or group not in names:
                continue
            seen_groups.add(group)
            if lines[-1] != "":
                lines.append("")
            lines.extend([_heading(1 + cut, f"{group} {names[group]}"), ""])
        marks = []
        if act.gates_cutover:
            marks.append("**GATES CUTOVER**")
        if act.kind is ActKind.UNBUILDABLE:
            marks.append("**NOT CODE HERE**")
        suffix = f" {' '.join(marks)}" if marks else ""
        lines.append(f"- [ ] `{act.leaf}` {act.text}{suffix}")
        if act.why:
            lines.append(f"  - {act.why}")
    lines.append("")
    return "\n".join(lines)


def main(repo: Path | None = None) -> int:
    """Write `docs/delivery-checklist.md`.

    `repo` is a parameter with the derived path as its default, for the reason
    `brain.status.main` gives for the same shape: a function that can only ever be pointed at
    this repository has a missing-file branch nothing can reach, and the branch that decides
    what happens when the work breakdown is absent is the one worth testing.
    """
    repo = Path(__file__).resolve().parents[3] if repo is None else repo
    wbs_path = _wbs_path(repo)
    if not wbs_path.exists():
        print(f"no WBS at {wbs_path}")
        return 1
    out = repo / "docs" / "delivery-checklist.md"
    out.write_text(checklist_markdown(wbs_path), encoding="utf-8", newline="\n")
    acts = load_acts(wbs_path)
    print(f"wrote {out.name}: {len(acts)} acts, {len(gated_acts(acts))} gating the cutover")
    return 0


if __name__ == "__main__":  # pragma: no cover  the module entry point, exercised by main()
    raise SystemExit(main())
