"""The console audit is served beside the decisions page, rendered rather than shown as markup.

`docs/console-audit/` is the audit `docs/admin-console.md` asks for, one file per area since
2026-09-28, and it is generated by the console's own tests. A document the owner is meant to read belongs at an address rather than in a
repository, and `/build/needs-rupash` is where this repository already serves a markdown document,
so the audit is served at `/build/console-audit` through the same renderer.

Task ids: M27.8.1, M27.10.1
"""

from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

from brain.app import create_app
from brain.docs_routes import (
    CONSOLE_AUDIT_DIRECTORY,
    CONSOLE_AUDIT_INDEX,
    DOCS,
    console_audit_text,
)


def test_the_console_audit_is_served_with_its_headings_and_tables_rendered() -> None:
    """Delete this and the audit can sit in `docs` with no address, or be served with its pipes
    and asterisks showing, which is a document nobody reads twice."""
    assert (DOCS / CONSOLE_AUDIT_DIRECTORY / CONSOLE_AUDIT_INDEX).exists()

    answer = TestClient(create_app()).get("/build/console-audit")

    assert answer.status_code == 200
    page = answer.text
    assert "<title>Console audit</title>" in page
    assert "<h1>The console audit</h1>" in page
    assert "<h3>" in page
    assert "<table><tr><th>" in page
    assert "**" not in page
    assert "| --- |" not in page


def test_the_decisions_page_keeps_its_own_title_now_that_the_renderer_is_shared() -> None:
    """The positive sibling for the shared renderer: the page it was written for still names
    itself. Delete this and the renderer can title every document after the first one."""
    page = TestClient(create_app()).get("/build/needs-rupash").text

    assert "<title>Needs Rupash</title>" in page
    assert "<title>Console audit</title>" not in page


def test_the_split_audit_is_served_as_one_page_index_first_and_every_area_after(
    tmp_path: Path,
) -> None:
    """The audit is one file per area so that two console changes do not meet on the same lines,
    and the page still has to read as one audit: the index first, then every other file in name
    order, and nothing at all when the index is missing.

    Delete this and the page can serve the index alone, which is an audit with every area missing
    that reads as an audit that found nothing."""
    audit = tmp_path / CONSOLE_AUDIT_DIRECTORY
    assert console_audit_text(tmp_path) is None

    audit.mkdir()
    (audit / "02-second.md").write_text("### Second\n", encoding="utf-8")
    (audit / "01-first.md").write_text("### First\n", encoding="utf-8")
    (audit / "not-administered.md").write_text("## Not here\n", encoding="utf-8")
    assert console_audit_text(tmp_path) is None

    (audit / CONSOLE_AUDIT_INDEX).write_text("# Index\n", encoding="utf-8")
    assert console_audit_text(tmp_path) == "# Index\n\n### First\n\n### Second\n\n## Not here\n"

    served = console_audit_text()
    assert served is not None
    for area in sorted((DOCS / CONSOLE_AUDIT_DIRECTORY).glob("[0-9]*.md")):
        assert area.read_text(encoding="utf-8") in served
