"""The console audit is served beside the decisions page, rendered rather than shown as markup.

`docs/console-audit.md` is the audit `docs/admin-console.md` asks for, and it is generated by the
console's own tests. A document the owner is meant to read belongs at an address rather than in a
repository, and `/build/needs-rupash` is where this repository already serves a markdown document,
so the audit is served at `/build/console-audit` through the same renderer.

Task ids: M27.8.1
"""

from __future__ import annotations

from fastapi.testclient import TestClient

from brain.app import create_app
from brain.docs_routes import CONSOLE_AUDIT_FILE, DOCS


def test_the_console_audit_is_served_with_its_headings_and_tables_rendered() -> None:
    """Delete this and the audit can sit in `docs` with no address, or be served with its pipes
    and asterisks showing, which is a document nobody reads twice."""
    assert (DOCS / CONSOLE_AUDIT_FILE).exists()

    answer = TestClient(create_app()).get("/build/console-audit")

    assert answer.status_code == 200
    page = answer.text
    assert "<title>Console audit</title>" in page
    assert "<h1>The console audit</h1>" in page
    assert "<h3>" in page
    assert "<table><tr><th>" in page
    assert "**" not in page
    assert "| --- |" not in page


def test_the_decisions_page_keeps_its_own_title_now_that_the_renderer_is_shared() -> None:
    """The positive sibling for the shared renderer: the page it was written for still names
    itself. Delete this and the renderer can title every document after the first one."""
    page = TestClient(create_app()).get("/build/needs-rupash").text

    assert "<title>Needs Rupash</title>" in page
    assert "<title>Console audit</title>" not in page
