"""The rules a migration must satisfy before it can merge.

Task ids: M31.2.2.2, M31.2.2.3, M31.2.2.4, M31.2.2.5
"""

from __future__ import annotations

from pathlib import Path

from brain.ops.migration_policy import Finding, check_all, check_file

NL = "\n"


def migration(up: list[str], down: list[str] | None = None) -> str:
    """Build a migration body from lines, so no test carries an unwieldy string literal."""
    body = "def upgrade() -> None:" + NL
    body += "".join(f"    {line}{NL}" for line in up)
    if down is not None:
        body += NL + "def downgrade() -> None:" + NL
        body += "".join(f"    {line}{NL}" for line in down)
    return body


def write(tmp_path: Path, body: str) -> Path:
    p = tmp_path / "0002_thing.py"
    p.write_text(body, encoding="utf-8")
    return p


def rules(findings: list[Finding]) -> set[str]:
    return {f.rule for f in findings}


# ----------------------------------------------------------- the real ones
def test_the_migrations_in_this_repository_pass() -> None:
    """The policy has to hold for what is already here, or it is aspirational."""
    assert check_all() == []


# ------------------------------------------------------------- autogenerate
def test_alembics_own_markers_mean_nobody_read_it(tmp_path: Path) -> None:
    """Autogenerate is very often nearly right, and nearly right passes review."""
    p = write(
        tmp_path,
        migration(
            ["### commands auto generated by Alembic ###", "pass"],
            ["op.drop_table('x')"],
        ),
    )
    assert "unreviewed autogeneration" in rules(check_file(p))


# ---------------------------------------------------------------- reversal
def test_a_missing_downgrade_is_a_deploy_with_no_way_back(tmp_path: Path) -> None:
    p = write(tmp_path, migration(["op.create_table('x')"]))
    assert "no downgrade" in rules(check_file(p))


def test_an_empty_downgrade_is_indistinguishable_from_forgetting(tmp_path: Path) -> None:
    """A genuinely one-way migration says so with NotImplementedError and a reason.
    `pass` says nothing, and cannot be told apart from having forgotten."""
    p = write(tmp_path, migration(["op.create_table('x')"], ["pass"]))
    assert "empty downgrade" in rules(check_file(p))


def test_an_empty_downgrade_is_still_empty_when_it_is_explained_at_length(
    tmp_path: Path,
) -> None:
    """The hole the test above did not cover, and the shape a gutted downgrade actually has.

    This rule was a line count: a body was flagged only if its last line was `pass` AND the
    whole body was two lines or fewer. So the moment somebody deleted the statements and left
    a docstring or commented the old call out, the file passed clean. That is not a contrived
    case, it is what deleting a downgrade looks like when the person is being conscientious
    about explaining themselves.

    Delete this and the check goes back to being satisfiable by writing more prose."""
    p = write(
        tmp_path,
        migration(
            ["op.create_table('x')"],
            [
                '"""Reverses the upgrade, dropping the table it created.',
                "",
                "    Left as a comment while the table is empty and nothing reads it.",
                '    """',
                "# op.drop_table('x')",
                "pass",
            ],
        ),
    )
    assert "empty downgrade" in rules(check_file(p))


def test_a_downgrade_that_does_one_real_thing_passes(tmp_path: Path) -> None:
    """So the parse cannot be tightened into refusing every downgrade, which would satisfy
    both tests above."""
    p = write(tmp_path, migration(["op.create_table('x')"], ["op.drop_table('x')"]))

    assert "empty downgrade" not in rules(check_file(p))
    assert "no downgrade" not in rules(check_file(p))


def test_a_migration_that_does_not_parse_is_reported_rather_than_passed_over(
    tmp_path: Path,
) -> None:
    """A file with a syntax error has no downgrade in any sense that matters. Returning
    "present" for it would make the one file nobody can run the one file nobody checks."""
    broken = "\n".join(["def downgrade() -> None", "    op.drop_table('x')", ""])
    p = write(tmp_path, broken)

    assert "no downgrade" in rules(check_file(p))


def test_a_deliberate_one_way_migration_is_accepted(tmp_path: Path) -> None:
    p = write(
        tmp_path,
        migration(
            ["op.create_table('x')"],
            ['raise NotImplementedError("the source rows are gone; restore from backup")'],
        ),
    )
    assert "empty downgrade" not in rules(check_file(p))
    assert "no downgrade" not in rules(check_file(p))


# ------------------------------------------------------------------ renames
def test_a_drop_plus_an_add_is_flagged_as_a_possible_rename(tmp_path: Path) -> None:
    """Autogenerate cannot tell a rename from a delete-and-create. On an empty database
    the two are identical; on a populated one the second silently destroys the data."""
    p = write(
        tmp_path,
        migration(
            ["op.drop_column('t', 'old')", "op.add_column('t', sa.Column('new', sa.String()))"],
            ["op.drop_column('t', 'new')"],
        ),
    )
    assert "possible rename written as drop plus add" in rules(check_file(p))


# ------------------------------------------------------------- not-null adds
def test_a_not_null_column_without_a_default_is_flagged(tmp_path: Path) -> None:
    """Works against an empty CI schema, fails against a populated table halfway through
    a production deploy - the worst possible moment to find out."""
    p = write(
        tmp_path,
        migration(
            ["op.add_column('t', sa.Column('c', sa.String(), nullable=False))"],
            ["op.drop_column('t', 'c')"],
        ),
    )
    assert "not-null column with no server_default" in rules(check_file(p))


def test_a_not_null_column_with_a_default_is_fine(tmp_path: Path) -> None:
    add = "op.add_column('t', sa.Column('c', sa.String(), nullable=False, server_default='x'))"
    p = write(tmp_path, migration([add], ["op.drop_column('t', 'c')"]))
    assert "not-null column with no server_default" not in rules(check_file(p))


# --------------------------------------------------------- schema plus data
def test_schema_and_data_in_one_migration_is_flagged(tmp_path: Path) -> None:
    """The schema half reverses cleanly and the data half usually cannot, so combining
    them makes the whole migration one-way."""
    p = write(
        tmp_path,
        migration(
            [
                "op.add_column('t', sa.Column('c', sa.String()))",
                "op.execute(\"UPDATE t SET c = 'x'\")",
            ],
            ["op.drop_column('t', 'c')"],
        ),
    )
    assert "schema and data change in one migration" in rules(check_file(p))


def test_a_pure_data_migration_is_not_flagged(tmp_path: Path) -> None:
    """Data-only is allowed; it is the mixture that cannot be reversed by halves."""
    p = write(
        tmp_path,
        migration(
            ["op.execute(\"UPDATE t SET c = 'x'\")"],
            ['op.execute("UPDATE t SET c = NULL")'],
        ),
    )
    assert "schema and data change in one migration" not in rules(check_file(p))


# ------------------------------------------------ row-level security, declared (M41.2.1)
def test_a_table_created_without_row_level_security_in_its_own_migration_is_reported(
    tmp_path: Path,
) -> None:
    """`brain.ops.sweeps rls` asks a live database and is therefore asked after the migration
    has merged, deployed and run. A table created in one revision and secured in a later one
    has no policy for the interval between them, and on an install from empty that interval
    sits inside one `alembic upgrade head`.

    Deleting this test moves the whole rule back to something only a runner with a database
    can answer, which is the position M41.2.1 exists to move it out of.
    """
    p = write(
        tmp_path,
        migration(
            ["op.create_table('widget', schema='gate')"],
            ["op.drop_table('widget', schema='gate')"],
        ),
    )
    assert "table created without row-level security" in rules(check_file(p))


def test_a_migration_securing_one_of_the_two_tables_it_creates_is_still_reported(
    tmp_path: Path,
) -> None:
    """The case that decides how the rule is written. A file creating two tables and securing
    one names both tables and says the words, so a check looking for the name and the words
    anywhere in the file passes for the table it left open, which is the only table the rule
    is about.

    Deleting this lets the exact match be relaxed to a substring search, and the relaxation
    reads like tidying.
    """
    p = write(
        tmp_path,
        migration(
            [
                "op.create_table('widget', schema='gate')",
                "op.create_table('gadget', schema='gate')",
                "op.execute('ALTER TABLE gate.widget ENABLE ROW LEVEL SECURITY')",
            ],
            ["op.drop_table('widget', schema='gate')"],
        ),
    )
    findings = [f for f in check_file(p) if f.rule == "table created without row-level security"]
    assert len(findings) == 1
    assert "gate.gadget" in findings[0].detail


def test_a_table_created_with_row_level_security_enabled_beside_it_passes(
    tmp_path: Path,
) -> None:
    """The positive half. A rule tested only by its refusals is satisfied by one that refuses
    every migration, and a migration policy that fails on correct work is a policy people
    route around.

    Deleting this leaves the rule provable only by breaking things, and the twenty-one
    migrations already here would be the only evidence it does not fire wrongly.
    """
    p = write(
        tmp_path,
        migration(
            [
                "op.create_table('widget', schema='gate')",
                "op.execute('ALTER TABLE gate.widget ENABLE ROW LEVEL SECURITY')",
            ],
            ["op.drop_table('widget', schema='gate')"],
        ),
    )
    assert "table created without row-level security" not in rules(check_file(p))


def test_a_table_created_outside_a_named_schema_is_reported(tmp_path: Path) -> None:
    """`brain.db` says every table lives in a named schema and never in `public`, because the
    schema is what the row-level security policies and the grant sweeps are written against.
    A table with no `schema=` lands in `public`, where the sweeps do not look.

    Deleting this lets a table arrive outside every schema the sweeps read, which is a table
    that passes the row-level security sweep by being invisible to it.
    """
    p = write(
        tmp_path,
        migration(["op.create_table('widget')"], ["op.drop_table('widget')"]),
    )
    assert "table created outside a named schema" in rules(check_file(p))


def test_a_migration_discussing_create_table_in_prose_creates_nothing(tmp_path: Path) -> None:
    """Half the migrations here argue about `op.create_table` in their docstrings. Reading the
    parse tree rather than the text is what stops the argument being counted as the act, and
    the failure mode of getting it wrong is a rule that fires on the files that explain
    themselves best.

    Deleting this lets the reader be rewritten as a text search, which is shorter and wrong.
    """
    body = (
        "\"\"\"This migration would use op.create_table('widget', schema='gate') if it "
        'created anything."""' + NL + NL + migration(["pass"], ["pass"])
    )
    p = write(tmp_path, body)
    assert rules(check_file(p)) == {"empty downgrade"}
