#!/bin/bash
# Generated by brain.deployment.install_script.render_install. Do not edit: edit the
# plan and regenerate, or the script and the plan disagree and the plan is the tested
# one.
set -euo pipefail

BRAIN_HOME="/opt/brain"
BRAIN_REPOSITORY="ghcr.io/rpsj2230/verz-brain-v2.0"
BRAIN_PROFILE=""
BRAIN_RELEASE=""
BRAIN_CONSOLE_ADDRESS=""
BRAIN_INSTALL_DOCKER="yes"
BRAIN_VAULT="yes"
BRAIN_ACCEPT_SWAP="no"
BRAIN_REFUSALS=0

say() { printf "%s\n" "$1"; }
fail() { printf "%s\n" "$1" >&2; exit 1; }
refuse() { printf "  %s\n" "$1" >&2; BRAIN_REFUSALS=$((BRAIN_REFUSALS + 1)); }
at_least() {
  test "$(printf "%s\n%s\n" "$2" "$1" | sort -V | sed -n "1p")" = "$2"
}
ask() {
  test -t 0 || fail "$2"
  printf "%s " "$1" >&2
  read -r BRAIN_ANSWER
  printf "%s" "$BRAIN_ANSWER"
}

usage() {
  say "usage: install.sh --release <tag> [--profile <name>] [--console-address <url>]"
  say ""
  say "  --profile                  one of: lite standard full. Asked for if you leave it out"
  say "  --release                  the release tag to install. Required, and never latest"
  say "  --console-address          the address your reverse proxy will serve the console on"
  say "  --no-install-docker        do not install Docker, say what to run instead"
  say "  --no-vault                 run no secrets vault, accepted only for: lite"
  say "  --accept-unencrypted-swap  go ahead although the vault's memory can reach plain swap"
  say "  --help                     print this and stop"
  say ""
  say "  BRAIN_RELEASE_URL must be set in the environment: it is the address of the release archive."
}

while test "$#" -gt 0; do
  case "$1" in
    --profile) BRAIN_PROFILE="${2:?--profile needs one of: lite standard full}"; shift 2 ;;
    --release) BRAIN_RELEASE="${2:?--release needs a release tag}"; shift 2 ;;
    --console-address) BRAIN_CONSOLE_ADDRESS="${2:?--console-address needs the address your reverse proxy will serve}"; shift 2 ;;
    --no-install-docker) BRAIN_INSTALL_DOCKER="no"; shift ;;
    --no-vault) BRAIN_VAULT="no"; shift ;;
    --accept-unencrypted-swap) BRAIN_ACCEPT_SWAP="yes"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) usage >&2; fail "unknown option: $1" ;;
  esac
done

test -n "$BRAIN_RELEASE" || { usage >&2; fail "--release is required and there is deliberately no default: a default of latest is what makes an install unpinned"; }
test "$BRAIN_RELEASE" != "latest" || fail "latest is not a release tag: installing it leaves this install unpinned, so the next pull changes the version with nobody deciding anything. Name the release you mean to install"

if test -z "$BRAIN_PROFILE"; then
  BRAIN_PROFILE="$(ask "Which profile? one of: lite standard full:" "--profile was not given and there is no terminal to ask at. Pass --profile with one of: lite standard full")"
fi
if test -z "$BRAIN_CONSOLE_ADDRESS" && test -t 0; then
  BRAIN_CONSOLE_ADDRESS="$(ask "What address will your reverse proxy serve the console on? (blank if you have not decided yet):" "pass --console-address, or leave it out: the install finishes either way")"
fi

case "$BRAIN_PROFILE" in
  lite) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.lite.yml"; BRAIN_WORKER_VAULT_FILES=""; BRAIN_SERVICES="4"; BRAIN_MEMORY_MIB="3968" ;;
  standard) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.yml -f /opt/brain/docker-compose.worker.yml -f /opt/brain/docker-compose.parse-worker.yml -f /opt/brain/docker-compose.objectstore.yml -f /opt/brain/docker-compose.keycloak.yml -f /opt/brain/docker-compose.inference.yml -f /opt/brain/docker-compose.presidio.yml"; BRAIN_WORKER_VAULT_FILES="-f /opt/brain/docker-compose.vault.worker.yml"; BRAIN_SERVICES="14"; BRAIN_MEMORY_MIB="11008" ;;
  full) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.yml -f /opt/brain/docker-compose.worker.yml -f /opt/brain/docker-compose.parse-worker.yml -f /opt/brain/docker-compose.objectstore.yml -f /opt/brain/docker-compose.keycloak.yml -f /opt/brain/docker-compose.langfuse.yml -f /opt/brain/docker-compose.inference.yml -f /opt/brain/docker-compose.automation.yml -f /opt/brain/docker-compose.matcher.yml -f /opt/brain/docker-compose.presidio.yml"; BRAIN_WORKER_VAULT_FILES="-f /opt/brain/docker-compose.vault.worker.yml"; BRAIN_SERVICES="22"; BRAIN_MEMORY_MIB="14976" ;;
  *) fail "unknown profile: $BRAIN_PROFILE. One of: lite standard full" ;;
esac
if test "$BRAIN_VAULT" = "no"; then
  case "$BRAIN_PROFILE" in
    lite) say "--no-vault: this install runs no secrets vault, so it keeps no provider key, relay password, signing secret or source key from the browser." ;;
    *) fail "--no-vault is refused for the $BRAIN_PROFILE profile: its worker signs every webhook delivery with a secret from the vault and its object store's key is read from there, so without one neither works. It is accepted for: lite" ;;
  esac
fi
BRAIN_RELEASE_URL="${BRAIN_RELEASE_URL:?set BRAIN_RELEASE_URL to the release archive for $BRAIN_RELEASE}"

say "Installing the $BRAIN_PROFILE profile of $BRAIN_RELEASE into $BRAIN_HOME, 24 steps."

# step 1 of 24: check this machine can run it
say "step 1 of 24: check this machine can run it"
say "  checking this machine against the requirements every install has"
test "$(uname -s)" = "Linux" || refuse "this machine runs $(uname -s). every container image this deployment pulls is linux/amd64 or linux/arm64, and the memory ceilings are enforced by the kernel rather than by docker"
case "$(uname -m)" in
  x86_64|aarch64|arm64) ;;
  *) refuse "this machine is $(uname -m), which is not 64-bit. every container image this deployment pulls is linux/amd64 or linux/arm64, and the memory ceilings are enforced by the kernel rather than by docker" ;;
esac
test -e "/sys/fs/cgroup/cgroup.controllers" || refuse "this kernel is not on the cgroup v2 unified hierarchy. every container image this deployment pulls is linux/amd64 or linux/arm64, and the memory ceilings are enforced by the kernel rather than by docker"
for one in curl tar; do
  command -v "$one" >/dev/null 2>&1 || refuse "$one is not installed. the installer fetches one release archive and unpacks it. It does not clone a repository, because a build that fetches a second repository is the shape brain.ops.independence.duplication_gaps refuses"
done
command -v openssl >/dev/null 2>&1 || refuse "openssl is not installed. every password and key is minted on this server during the install, and a generator that is not a CSPRNG is a credential somebody can reproduce"
BRAIN_SWAP_PLAIN=""
if test "$BRAIN_VAULT" != "no" && test -r /proc/swaps; then
  while read -r BRAIN_SWAP _; do
    case "$BRAIN_SWAP" in
      Filename|/dev/zram*) ;;
      /dev/dm-*) grep -q "^CRYPT-" "/sys/block/${BRAIN_SWAP#/dev/}/dm/uuid" 2>/dev/null || BRAIN_SWAP_PLAIN="$BRAIN_SWAP_PLAIN $BRAIN_SWAP" ;;
      *) BRAIN_SWAP_PLAIN="$BRAIN_SWAP_PLAIN $BRAIN_SWAP" ;;
    esac
  done < /proc/swaps
fi
if test -n "$BRAIN_SWAP_PLAIN"; then
  say "  note: this machine swaps to$BRAIN_SWAP_PLAIN, which is not encrypted. the secrets vault keeps decrypted keys in memory, and OpenBao 2.4 no longer locks that memory, so swap can write those keys to disk unencrypted. To remove the risk, turn swap off (swapoff -a, and delete the swap line from /etc/fstab) or move it onto dm-crypt; zram stays in memory and is fine"
  if test "$BRAIN_ACCEPT_SWAP" = "yes"; then
    say "  accepted: unencrypted swap, by --accept-unencrypted-swap"
  elif test -t 0 && test "$(ask "Type yes to continue with unencrypted swap:" "--accept-unencrypted-swap was not given")" = "yes"; then
    say "  accepted: unencrypted swap, by typing yes at this terminal"
  else
    refuse "unencrypted swap was not accepted. To go ahead with it, run again and type yes at the prompt, or pass --accept-unencrypted-swap. the secrets vault keeps decrypted keys in memory, and OpenBao 2.4 no longer locks that memory, so swap can write those keys to disk unencrypted. To remove the risk, turn swap off (swapoff -a, and delete the swap line from /etc/fstab) or move it onto dm-crypt; zram stays in memory and is fine"
  fi
fi
say "  note: a reverse proxy terminating TLS on 443 is part of this install and nothing running on this machine can check for it. Every service uses \`expose\` and none uses \`ports\`, so after a complete install the console is reachable from other containers and from nowhere else. That is right for the database, the cache and the pooler, and it means the reverse proxy holding the certificate is part of the install rather than an optional extra. No compose file in this repository declares one, so it is a requirement on the server and not on the stack. See docs/install/network.md."
test "$BRAIN_REFUSALS" -eq 0 || fail "this machine cannot run it yet, for the reasons above. Nothing has been written. When a reason is one you cannot fix on this machine, docs/install/install.md has the sequence by hand"

# step 2 of 24: install docker if it is missing
if test "$BRAIN_INSTALL_DOCKER" = "no" || { command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; }; then
  say "step 2 of 24: install docker if it is missing - already done, skipping"
else
  say "step 2 of 24: install docker if it is missing"
  test -r "/etc/os-release" || fail "there is no /etc/os-release on this machine, so nothing here can tell which install route Docker documents for it. Install Docker Engine and the compose plugin yourself: https://docs.docker.com/engine/install/"
  BRAIN_OS_ID="$(. /etc/os-release && printf "%s" "${ID:-} ${ID_LIKE:-}")"
  test "$(id -u)" -eq 0 || fail "installing Docker needs root and this is not a root shell. Run this again with sudo, or install Docker Engine and the compose plugin yourself: https://docs.docker.com/engine/install/"
  BRAIN_DOCKER_ROUTE=""
  for one in $BRAIN_OS_ID; do
    case "$one" in
      debian|ubuntu) BRAIN_DOCKER_ROUTE="apt $one" ;;
      almalinux|centos|fedora|rhel|rocky) BRAIN_DOCKER_ROUTE="dnf $one" ;;
      *) continue ;;
    esac
    break
  done
  test -n "$BRAIN_DOCKER_ROUTE" || fail "this is $BRAIN_OS_ID, and the routes Docker documents and this script knows are: debian ubuntu almalinux centos fedora rhel rocky. Install Docker Engine 24 or newer with the compose plugin by the route your distribution documents, then run this again: https://docs.docker.com/engine/install/"
  say "  installing Docker by the $BRAIN_DOCKER_ROUTE route Docker documents"
  case "$BRAIN_DOCKER_ROUTE" in
    apt*)
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y ca-certificates curl
      install -m 0755 -d "/etc/apt/keyrings"
      curl -fsSL "https://download.docker.com/linux/${BRAIN_DOCKER_ROUTE#apt }/gpg" -o "/etc/apt/keyrings/docker.asc"
      chmod a+r "/etc/apt/keyrings/docker.asc"
      printf "deb [arch=%s signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/%s %s stable\n" "$(dpkg --print-architecture)" "${BRAIN_DOCKER_ROUTE#apt }" "$(. /etc/os-release && printf "%s" "${VERSION_CODENAME:-}")" > "/etc/apt/sources.list.d/docker.list"
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ;;
    dnf*)
      dnf -y install dnf-plugins-core
      dnf -y config-manager --add-repo "https://download.docker.com/linux/${BRAIN_DOCKER_ROUTE#dnf }/docker-ce.repo"
      dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ;;
  esac
  systemctl enable --now docker || fail "Docker installed and its daemon would not start. Read the output of systemctl status docker, start it, then run this again. Nothing of this install has been written yet"
fi

# step 3 of 24: check the docker on this machine is new enough
say "step 3 of 24: check the docker on this machine is new enough"
BRAIN_ENGINE="$(docker version --format "{{.Server.Version}}" 2>/dev/null || true)"
if test -z "$BRAIN_ENGINE"; then
  refuse "the docker daemon on this machine is not answering, and 24.0 or newer is needed. the compose files use the Compose specification's \`deploy\` block, healthcheck \`start_period\` and \`depends_on\` conditions, and an older engine starts the dependent container before its dependency is ready"
elif ! at_least "$BRAIN_ENGINE" "24.0"; then
  refuse "this machine runs Docker Engine $BRAIN_ENGINE, and 24.0 or newer is needed. the compose files use the Compose specification's \`deploy\` block, healthcheck \`start_period\` and \`depends_on\` conditions, and an older engine starts the dependent container before its dependency is ready"
fi
BRAIN_COMPOSE_VERSION="$(docker compose version --short 2>/dev/null || true)"
if test -z "$BRAIN_COMPOSE_VERSION"; then
  refuse "this machine has no docker compose subcommand, which usually means the older docker-compose is installed instead, and 2.10 or newer is needed. Every memory ceiling in this deployment is written under deploy.resources.limits, and the v1 docker-compose tool ignores that block silently. An install on the old tool comes up healthy with every container unlimited and nothing anywhere says so, which turns the whole of brain.ops.wiring into a document about a deployment that is not running."
elif ! at_least "$BRAIN_COMPOSE_VERSION" "2.10"; then
  refuse "this machine runs compose $BRAIN_COMPOSE_VERSION, and 2.10 or newer is needed. Every memory ceiling in this deployment is written under deploy.resources.limits, and the v1 docker-compose tool ignores that block silently. An install on the old tool comes up healthy with every container unlimited and nothing anywhere says so, which turns the whole of brain.ops.wiring into a document about a deployment that is not running."
fi
test "$BRAIN_REFUSALS" -eq 0 || fail "the Docker on this machine is not one this deployment can run, for the reasons above. Nothing has been written"

# step 4 of 24: check the machine
say "step 4 of 24: check the machine"
command -v docker >/dev/null || fail "docker is not installed"
docker compose version >/dev/null 2>&1 || fail "docker compose v2 is not installed"

# step 5 of 24: check the machine is large enough
say "step 5 of 24: check the machine is large enough"
available=$(awk '/MemTotal/ {print int($2 / 1024)}' /proc/meminfo)
test "$available" -ge "$BRAIN_MEMORY_MIB" || fail "this profile needs $BRAIN_MEMORY_MIB MiB and this machine has $available MiB"

# step 6 of 24: create the install directory
if test -d "/opt/brain"; then
  say "step 6 of 24: create the install directory - already done, skipping"
else
  say "step 6 of 24: create the install directory"
  mkdir -p "/opt/brain"
fi

# step 7 of 24: download and unpack the release
if test -f "/opt/brain/RELEASE" && test "$(cat "/opt/brain/RELEASE")" = "$BRAIN_RELEASE"; then
  say "step 7 of 24: download and unpack the release - already done, skipping"
else
  say "step 7 of 24: download and unpack the release"
  curl -fsSL "$BRAIN_RELEASE_URL" -o "/opt/brain/release.tar.gz"
  tar -xzf "/opt/brain/release.tar.gz" -C "/opt/brain" --strip-components=1
  printf "%s\n" "$BRAIN_RELEASE" > "/opt/brain/RELEASE"
fi

# step 8 of 24: change into the release directory
say "step 8 of 24: change into the release directory"
cd "/opt/brain" || fail "the release did not unpack into /opt/brain"

# step 9 of 24: write the environment file from the template
if test -f "/opt/brain/.env"; then
  say "step 9 of 24: write the environment file from the template - already done, skipping"
else
  say "step 9 of 24: write the environment file from the template"
  test -f "/opt/brain/.env" || cp "/opt/brain/.env.example" "/opt/brain/.env"
fi

# step 10 of 24: pin the image this install runs
if grep -qxF "APP_IMAGE=$BRAIN_REPOSITORY:$BRAIN_RELEASE" "/opt/brain/.env"; then
  say "step 10 of 24: pin the image this install runs - already done, skipping"
else
  say "step 10 of 24: pin the image this install runs"
  umask 077
  {
    grep -v "^APP_IMAGE=" "/opt/brain/.env" || true
    printf "APP_IMAGE=%s\n" "$BRAIN_REPOSITORY:$BRAIN_RELEASE"
  } > "/opt/brain/.env.pinned"
  mv "/opt/brain/.env.pinned" "/opt/brain/.env"
fi

# step 11 of 24: create the settings the containers mount
if test -f "/opt/brain/settings/automation/egress.conf" && test -f "/opt/brain/settings/langfuse/clickhouse-memory.xml" && test -f "/opt/brain/settings/seaweedfs/provision.sh" && test -f "/opt/brain/settings/seaweedfs/s3.json"; then
  say "step 11 of 24: create the settings the containers mount - already done, skipping"
else
  say "step 11 of 24: create the settings the containers mount"
  mkdir -p "/opt/brain/settings/automation" "/opt/brain/settings/langfuse" "/opt/brain/settings/seaweedfs"
  test -f "/opt/brain/settings/automation/egress.conf" || cp "/opt/brain/ops/automation/egress.conf" "/opt/brain/settings/automation/egress.conf"
  test -f "/opt/brain/settings/langfuse/clickhouse-memory.xml" || cp "/opt/brain/ops/langfuse/clickhouse-memory.xml" "/opt/brain/settings/langfuse/clickhouse-memory.xml"
  test -f "/opt/brain/settings/seaweedfs/provision.sh" || cp "/opt/brain/ops/seaweedfs/provision.sh" "/opt/brain/settings/seaweedfs/provision.sh"
  test -f "/opt/brain/settings/seaweedfs/s3.json" || cp "/opt/brain/ops/seaweedfs/s3.json" "/opt/brain/settings/seaweedfs/s3.json"
fi

# step 12 of 24: mint this installation's secrets
if grep -q "^POSTGRES_PASSWORD=." "/opt/brain/.env"; then
  say "step 12 of 24: mint this installation's secrets - already done, skipping"
else
  say "step 12 of 24: mint this installation's secrets"
  umask 077
  {
    printf "POSTGRES_PASSWORD=%s\n" "$(openssl rand -hex 32)"
    printf "APP_ROLE_PASSWORD=%s\n" "$(openssl rand -hex 32)"
    printf "BRAIN_SETUP_SECRET=%s\n" "$(openssl rand -hex 32)"
    printf "BRAIN_SETUP_ISSUED_AT=%s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >> "/opt/brain/.env"
fi

# step 13 of 24: start the secrets vault
if test "${BRAIN_VAULT:-yes}" = "no" || docker compose -f "/opt/brain/ops/openbao/compose.yml" ps --status running --services | grep -qx vault; then
  say "step 13 of 24: start the secrets vault - already done, skipping"
else
  say "step 13 of 24: start the secrets vault"
  docker compose -f "/opt/brain/ops/openbao/compose.yml" up -d
  BRAIN_VAULT_ANSWER=1
  for _ in $(seq 1 30); do
    BRAIN_VAULT_ANSWER=0
    docker exec -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao operator init -status >/dev/null 2>&1 || BRAIN_VAULT_ANSWER="$?"
    test "$BRAIN_VAULT_ANSWER" -ne 1 && break
    sleep 2
  done
  test "$BRAIN_VAULT_ANSWER" -ne 1 || fail "the secrets vault started and never answered. Read docker logs brain-vault, then run this again"
fi

# step 14 of 24: initialise the secrets vault and show its unseal pieces, once
if test "${BRAIN_VAULT:-yes}" = "no" || docker exec -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao operator init -status >/dev/null 2>&1; then
  say "step 14 of 24: initialise the secrets vault and show its unseal pieces, once - already done, skipping"
else
  say "step 14 of 24: initialise the secrets vault and show its unseal pieces, once"
  BRAIN_VAULT_INIT="$(docker exec -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao operator init -key-shares=5 -key-threshold=3)" || fail "the secrets vault refused to initialise, so no piece was made and nothing is lost. Read docker logs brain-vault, then run this again"
  say ""
  say "The secrets vault's unseal key, in 5 pieces. Any 3 of them open the vault."
  say "This is the only time they are shown. Nothing on this server keeps them, and nothing can show them again."
  if test "$(printf "%s\n" "$BRAIN_VAULT_INIT" | grep -c "^Unseal Key ")" -eq 5; then
    printf "%s\n" "$BRAIN_VAULT_INIT" | sed -n "s/^Unseal Key \([0-9]*\): /  piece \1 of 5: /p"
  else
    say "The vault answered in a shape this installer cannot read, so its whole answer is below: the pieces and the root token are in it. Keep the pieces as the next lines say, and finish by hand with ops/openbao/UNSEAL.md."
    printf "%s\n" "$BRAIN_VAULT_INIT"
    fail "the vault is initialised and this installer could not read its answer. Finish by hand with ops/openbao/UNSEAL.md, under Finishing what the installer began"
  fi
  say ""
  say "Give each piece to a different person now, each by a different route, and keep none of them on this server. After any restart of the vault, 3 of those people open it again: ops/openbao/UNSEAL.md, under After a restart."
  say "If this terminal is being recorded, or this run is going through tee or into a log, that record now holds the pieces. Destroy it."
  if test -t 0; then
    printf "%s " "Press Enter once every piece is somewhere other than this server:" >&2
    read -r BRAIN_ANSWER
  fi
fi

# step 15 of 24: open the secrets vault and give this install its tokens
if test "${BRAIN_VAULT:-yes}" = "no" || { grep -q "^BRAIN_VAULT_ADDRESS=." "/opt/brain/.env" && grep -q "^BRAIN_VAULT_TOKEN=." "/opt/brain/.env" && { test -z "${BRAIN_WORKER_VAULT_FILES:-}" || grep -q "^BRAIN_WORKER_VAULT_TOKEN=." "/opt/brain/.env"; }; }; then
  say "step 15 of 24: open the secrets vault and give this install its tokens - already done, skipping"
else
  say "step 15 of 24: open the secrets vault and give this install its tokens"
  test -n "${BRAIN_VAULT_INIT:-}" || fail "the secrets vault on this server was initialised by an earlier run that stopped before this step, and the root token this step needs existed only in that run. Finish it by hand with ops/openbao/UNSEAL.md, under Finishing what the installer began"
  vault_piece() { printf "%s\n" "$BRAIN_VAULT_INIT" | sed -n "s/^Unseal Key $1: //p"; }
  vault_root() { printf "%s\n" "$BRAIN_VAULT_INIT" | sed -n "s/^Initial Root Token: //p"; }
  as_vault_root() { BAO_TOKEN="$(vault_root)" docker exec -e BAO_TOKEN -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao "$@" </dev/null; }
  as_vault_root_reading() { BAO_TOKEN="$(vault_root)" docker exec -i -e BAO_TOKEN -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao "$@"; }
  for piece in $(seq 1 3); do
    printf "%s" "$(vault_piece "$piece")" | docker exec -i -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao write sys/unseal key=- >/dev/null
  done
  docker exec -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao status >/dev/null 2>&1 || fail "the vault is still sealed after 3 of its pieces. Nothing has been written to the environment file. Open it with ops/openbao/UNSEAL.md, then finish by hand under Finishing what the installer began"
  BRAIN_VAULT_ENGINES="$(as_vault_root secrets list)" || fail "the vault would not list its engines under the root token. Finish by hand with ops/openbao/UNSEAL.md, under Finishing what the installer began"
  for engine in providers webhooks connector_keys; do
    case "$BRAIN_VAULT_ENGINES" in
      *"$engine/ "*) ;;
      *) as_vault_root secrets enable -path="$engine" kv-v2 >/dev/null ;;
    esac
  done
  for policy in "/opt/brain/ops/openbao/policies/"*.hcl; do
    tr -d "\015" < "$policy" | as_vault_root_reading policy write "$(basename "$policy" .hcl)" - >/dev/null
  done
  as_vault_root write auth/token/roles/connector-run allowed_policies=connector-run orphan=false renewable=false token_no_default_policy=true token_explicit_max_ttl=3600 >/dev/null || fail "the vault would not create the connector-run token role. Finish by hand with ops/openbao/UNSEAL.md, under Finishing what the installer began"
  as_vault_root kv metadata put -mount=connector_keys -custom-metadata='scopes=an agent API key with read access' -custom-metadata='not_requested=an admin key, which can change SLAs and delete tickets' freshdesk >/dev/null || fail "the vault would not define the credential slot for freshdesk. Finish by hand with ops/openbao/credential-slots.md"
  as_vault_root kv metadata put -mount=connector_keys -custom-metadata='scopes=read on the named shared drive only' -custom-metadata='not_requested=domain-wide delegation' google_drive >/dev/null || fail "the vault would not define the credential slot for google_drive. Finish by hand with ops/openbao/credential-slots.md"
  as_vault_root kv metadata put -mount=connector_keys -custom-metadata='scopes=crm.objects.contacts.read; crm.objects.deals.read' -custom-metadata='not_requested=crm.objects.*.write; anything touching settings' hubspot >/dev/null || fail "the vault would not define the credential slot for hubspot. Finish by hand with ops/openbao/credential-slots.md"
  as_vault_root kv metadata put -mount=connector_keys -custom-metadata='scopes=SELECT on the allowlisted views only' -custom-metadata='not_requested=SELECT on tables; any write' laravel >/dev/null || fail "the vault would not define the credential slot for laravel. Finish by hand with ops/openbao/credential-slots.md"
  as_vault_root kv metadata put -mount=connector_keys -custom-metadata='scopes=bitable:app:readonly; base:record:read' -custom-metadata='not_requested=base:record:write; drive:drive' lark_base >/dev/null || fail "the vault would not define the credential slot for lark_base. Finish by hand with ops/openbao/credential-slots.md"
  as_vault_root kv metadata put -mount=connector_keys -custom-metadata='scopes=wiki:wiki:readonly' -custom-metadata='not_requested=docs:document edit scopes' lark_wiki >/dev/null || fail "the vault would not define the credential slot for lark_wiki. Finish by hand with ops/openbao/credential-slots.md"
  as_vault_root kv metadata put -mount=connector_keys -custom-metadata='scopes=accounting.transactions.read; accounting.contacts.read' -custom-metadata='not_requested=any .write scope' xero >/dev/null || fail "the vault would not define the credential slot for xero. Finish by hand with ops/openbao/credential-slots.md"
  BRAIN_VAULT_APP_TOKEN="$(as_vault_root token create -policy=application -orphan -period=768h -field=token)" || fail "the vault would not mint the application's token. Finish by hand with ops/openbao/UNSEAL.md, under Finishing what the installer began"
  BRAIN_VAULT_WORKER_TOKEN=""
  if test -n "${BRAIN_WORKER_VAULT_FILES:-}"; then
    BRAIN_VAULT_WORKER_TOKEN="$(as_vault_root token create -policy=worker -orphan -period=768h -field=token)" || fail "the vault would not mint the worker's token. Finish by hand with ops/openbao/UNSEAL.md, under Finishing what the installer began"
  fi
  BAO_TOKEN="$BRAIN_VAULT_APP_TOKEN" docker exec -e BAO_TOKEN -e BAO_ADDR=http://127.0.0.1:8200 brain-vault bao token lookup >/dev/null </dev/null || fail "the application's new token was refused by the vault that minted it. Nothing has been written; finish by hand with ops/openbao/UNSEAL.md"
  umask 077
  {
    printf "BRAIN_VAULT_ADDRESS=%s\n" "http://vault:8200"
    printf "BRAIN_VAULT_TOKEN=%s\n" "$BRAIN_VAULT_APP_TOKEN"
    if test -n "${BRAIN_WORKER_VAULT_FILES:-}"; then
      printf "BRAIN_WORKER_VAULT_TOKEN=%s\n" "$BRAIN_VAULT_WORKER_TOKEN"
    fi
  } >> "/opt/brain/.env"
  as_vault_root token revoke -self >/dev/null || fail "the tokens are written and the root token could not be revoked. Revoke it by hand now: ops/openbao/UNSEAL.md, under Finishing what the installer began"
  unset BRAIN_VAULT_INIT BRAIN_VAULT_APP_TOKEN BRAIN_VAULT_WORKER_TOKEN
fi

# step 16 of 24: compose the secrets vault in
say "step 16 of 24: compose the secrets vault in"
if grep -q "^BRAIN_VAULT_ADDRESS=." "/opt/brain/.env" 2>/dev/null; then BRAIN_COMPOSE_FILES="$BRAIN_COMPOSE_FILES -f /opt/brain/docker-compose.vault.yml"; say "The environment file names a secrets vault, so the vault overlay is composed in."; fi
if test -n "${BRAIN_WORKER_VAULT_FILES:-}" && grep -q "^BRAIN_WORKER_VAULT_TOKEN=." "/opt/brain/.env" 2>/dev/null; then BRAIN_COMPOSE_FILES="$BRAIN_COMPOSE_FILES $BRAIN_WORKER_VAULT_FILES"; say "The environment file holds the worker's vault token, so its overlay is composed in."; fi

# step 17 of 24: pull the images this profile runs
if docker compose $BRAIN_COMPOSE_FILES images --quiet | grep -q .; then
  say "step 17 of 24: pull the images this profile runs - already done, skipping"
else
  say "step 17 of 24: pull the images this profile runs"
  docker compose $BRAIN_COMPOSE_FILES pull --quiet
fi

# step 18 of 24: start the database and wait for it
if docker compose $BRAIN_COMPOSE_FILES ps --status running --services | grep -qx db; then
  say "step 18 of 24: start the database and wait for it - already done, skipping"
else
  say "step 18 of 24: start the database and wait for it"
  docker compose $BRAIN_COMPOSE_FILES up -d db
  docker compose $BRAIN_COMPOSE_FILES exec -T db sh -c 'until pg_isready -U brain -d brain; do sleep 2; done'
fi

# step 19 of 24: create the databases the compose files do not
if ! docker compose $BRAIN_COMPOSE_FILES config --services | grep -qx langfuse-web || docker compose $BRAIN_COMPOSE_FILES exec -T db psql -tAc "select 1 from pg_database where datname = 'langfuse'" -U brain -d brain | grep -qx 1; then
  say "step 19 of 24: create the databases the compose files do not - already done, skipping"
else
  say "step 19 of 24: create the databases the compose files do not"
  if docker compose $BRAIN_COMPOSE_FILES config --services | grep -qx langfuse-web; then
    grep -q "^LANGFUSE_POSTGRES_PASSWORD=." "/opt/brain/.env" || fail "set LANGFUSE_POSTGRES_PASSWORD in /opt/brain/.env: this profile runs the trace ledger and it signs in with it"
    docker compose $BRAIN_COMPOSE_FILES exec -T db psql -tAc "select 1 from pg_roles where rolname = 'langfuse'" -U brain -d brain | grep -qx 1 || sed -n "s/^LANGFUSE_POSTGRES_PASSWORD=\(.*\)/create role langfuse login password '\1';/p" "/opt/brain/.env" | docker compose $BRAIN_COMPOSE_FILES exec -T db psql -v ON_ERROR_STOP=1 -U brain -d brain
    docker compose $BRAIN_COMPOSE_FILES exec -T db psql -tAc "select 1 from pg_database where datname = 'langfuse'" -U brain -d brain | grep -qx 1 || docker compose $BRAIN_COMPOSE_FILES exec -T db psql -v ON_ERROR_STOP=1 -U brain -d brain -c "create database langfuse owner langfuse"
  fi
fi

# step 20 of 24: start everything else
if test "$(docker compose $BRAIN_COMPOSE_FILES ps --status running --services | wc -l)" -ge "$BRAIN_SERVICES"; then
  say "step 20 of 24: start everything else - already done, skipping"
else
  say "step 20 of 24: start everything else"
  docker compose $BRAIN_COMPOSE_FILES up -d
fi

# step 21 of 24: wait for the application to report ready
say "step 21 of 24: wait for the application to report ready"
for _ in $(seq 1 60); do
  docker compose $BRAIN_COMPOSE_FILES exec -T app python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen("http://127.0.0.1:8000/health/ready",timeout=4).status==200 else 1)' && break
  sleep 5
done
docker compose $BRAIN_COMPOSE_FILES exec -T app python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen("http://127.0.0.1:8000/health/ready",timeout=4).status==200 else 1)' || fail "the application never reported ready"

# step 22 of 24: furnish the install
if docker compose $BRAIN_COMPOSE_FILES exec -T db psql -tAc "select 1 from ops.setting where key = 'starter.furnished'" -U brain -d brain | grep -qx 1; then
  say "step 22 of 24: furnish the install - already done, skipping"
else
  say "step 22 of 24: furnish the install"
  docker compose $BRAIN_COMPOSE_FILES exec -T app python -m brain.ops.starter_store
fi

# step 23 of 24: present the setup code, once
say "step 23 of 24: present the setup code, once"
printf "setup code: %s\n" "$(grep BRAIN_SETUP_SECRET "/opt/brain/.env" | cut -d= -f2)"
printf "%s\n" "Open the console and enter it on the first screen. It is required before anybody can claim this system."

# step 24 of 24: say where to go next
say "step 24 of 24: say where to go next"
say ""
if test -n "$BRAIN_CONSOLE_ADDRESS"; then
  printf "Open %s/first-run and enter the code above.\n" "${BRAIN_CONSOLE_ADDRESS%/}"
else
  say "No service in this deployment publishes a port, so the console answers on whatever address your reverse proxy sends to the app service. Open /first-run on that address and enter the code above."
fi
say "Sign in there first, then enter the code: it is held in that one browser tab and a reload loses it."
say "Until somebody does, this system has no administrator and whoever opens that address first becomes one."
say "docs/install/install.md, under The setup code, is the rest of it."

say "Done. The $BRAIN_PROFILE profile is running from $BRAIN_HOME."
