#!/bin/bash
# Generated by brain.deployment.install_script.render_install. Do not edit: edit the
# plan and regenerate, or the script and the plan disagree and the plan is the tested
# one.
set -euo pipefail

BRAIN_HOME="/opt/brain"
BRAIN_REPOSITORY="ghcr.io/rpsj2230/verz-brain-v2.0"
BRAIN_PROFILE=""
BRAIN_RELEASE=""
BRAIN_CONSOLE_ADDRESS=""
BRAIN_INSTALL_DOCKER="yes"
BRAIN_REFUSALS=0

say() { printf "%s\n" "$1"; }
fail() { printf "%s\n" "$1" >&2; exit 1; }
refuse() { printf "  %s\n" "$1" >&2; BRAIN_REFUSALS=$((BRAIN_REFUSALS + 1)); }
at_least() {
  test "$(printf "%s\n%s\n" "$2" "$1" | sort -V | sed -n "1p")" = "$2"
}
ask() {
  test -t 0 || fail "$2"
  printf "%s " "$1" >&2
  read -r BRAIN_ANSWER
  printf "%s" "$BRAIN_ANSWER"
}

usage() {
  say "usage: install.sh --release <tag> [--profile <name>] [--console-address <url>]"
  say ""
  say "  --profile            one of: lite standard full. Asked for if you leave it out"
  say "  --release            the release tag to install. Required, and never latest"
  say "  --console-address    the address your reverse proxy will serve the console on"
  say "  --no-install-docker  do not install Docker, say what to run instead"
  say "  --help               print this and stop"
  say ""
  say "  BRAIN_RELEASE_URL must be set in the environment: it is the address of the release archive."
}

while test "$#" -gt 0; do
  case "$1" in
    --profile) BRAIN_PROFILE="${2:?--profile needs one of: lite standard full}"; shift 2 ;;
    --release) BRAIN_RELEASE="${2:?--release needs a release tag}"; shift 2 ;;
    --console-address) BRAIN_CONSOLE_ADDRESS="${2:?--console-address needs the address your reverse proxy will serve}"; shift 2 ;;
    --no-install-docker) BRAIN_INSTALL_DOCKER="no"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) usage >&2; fail "unknown option: $1" ;;
  esac
done

test -n "$BRAIN_RELEASE" || { usage >&2; fail "--release is required and there is deliberately no default: a default of latest is what makes an install unpinned"; }
test "$BRAIN_RELEASE" != "latest" || fail "latest is not a release tag: installing it leaves this install unpinned, so the next pull changes the version with nobody deciding anything. Name the release you mean to install"

if test -z "$BRAIN_PROFILE"; then
  BRAIN_PROFILE="$(ask "Which profile? one of: lite standard full:" "--profile was not given and there is no terminal to ask at. Pass --profile with one of: lite standard full")"
fi
if test -z "$BRAIN_CONSOLE_ADDRESS" && test -t 0; then
  BRAIN_CONSOLE_ADDRESS="$(ask "What address will your reverse proxy serve the console on? (blank if you have not decided yet):" "pass --console-address, or leave it out: the install finishes either way")"
fi

case "$BRAIN_PROFILE" in
  lite) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.lite.yml"; BRAIN_SERVICES="4"; BRAIN_MEMORY_MIB="3968" ;;
  standard) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.yml -f /opt/brain/docker-compose.worker.yml -f /opt/brain/docker-compose.parse-worker.yml -f /opt/brain/docker-compose.objectstore.yml -f /opt/brain/docker-compose.keycloak.yml -f /opt/brain/docker-compose.inference.yml"; BRAIN_SERVICES="12"; BRAIN_MEMORY_MIB="9920" ;;
  full) BRAIN_COMPOSE_FILES="-f /opt/brain/docker-compose.yml -f /opt/brain/docker-compose.worker.yml -f /opt/brain/docker-compose.parse-worker.yml -f /opt/brain/docker-compose.objectstore.yml -f /opt/brain/docker-compose.keycloak.yml -f /opt/brain/docker-compose.langfuse.yml -f /opt/brain/docker-compose.inference.yml -f /opt/brain/docker-compose.automation.yml -f /opt/brain/docker-compose.matcher.yml"; BRAIN_SERVICES="20"; BRAIN_MEMORY_MIB="13888" ;;
  *) fail "unknown profile: $BRAIN_PROFILE. One of: lite standard full" ;;
esac
BRAIN_RELEASE_URL="${BRAIN_RELEASE_URL:?set BRAIN_RELEASE_URL to the release archive for $BRAIN_RELEASE}"

say "Installing the $BRAIN_PROFILE profile of $BRAIN_RELEASE into $BRAIN_HOME, 19 steps."

# step 1 of 19: check this machine can run it
say "step 1 of 19: check this machine can run it"
say "  checking this machine against the requirements every install has"
test "$(uname -s)" = "Linux" || refuse "this machine runs $(uname -s). every container image this deployment pulls is linux/amd64 or linux/arm64, and the memory ceilings are enforced by the kernel rather than by docker"
case "$(uname -m)" in
  x86_64|aarch64|arm64) ;;
  *) refuse "this machine is $(uname -m), which is not 64-bit. every container image this deployment pulls is linux/amd64 or linux/arm64, and the memory ceilings are enforced by the kernel rather than by docker" ;;
esac
test -e "/sys/fs/cgroup/cgroup.controllers" || refuse "this kernel is not on the cgroup v2 unified hierarchy. every container image this deployment pulls is linux/amd64 or linux/arm64, and the memory ceilings are enforced by the kernel rather than by docker"
for one in curl tar; do
  command -v "$one" >/dev/null 2>&1 || refuse "$one is not installed. the installer fetches one release archive and unpacks it. It does not clone a repository, because a build that fetches a second repository is the shape brain.ops.independence.duplication_gaps refuses"
done
command -v openssl >/dev/null 2>&1 || refuse "openssl is not installed. every password and key is minted on this server during the install, and a generator that is not a CSPRNG is a credential somebody can reproduce"
say "  note: a reverse proxy terminating TLS on 443 is part of this install and nothing running on this machine can check for it. Every service uses \`expose\` and none uses \`ports\`, so after a complete install the console is reachable from other containers and from nowhere else. That is right for the database, the cache and the pooler, and it means the reverse proxy holding the certificate is part of the install rather than an optional extra. No compose file in this repository declares one, so it is a requirement on the server and not on the stack. See docs/install/network.md."
test "$BRAIN_REFUSALS" -eq 0 || fail "this machine cannot run it yet, for the reasons above. Nothing has been written. When a reason is one you cannot fix on this machine, docs/install/install.md has the sequence by hand"

# step 2 of 19: install docker if it is missing
if test "$BRAIN_INSTALL_DOCKER" = "no" || { command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; }; then
  say "step 2 of 19: install docker if it is missing - already done, skipping"
else
  say "step 2 of 19: install docker if it is missing"
  test -r "/etc/os-release" || fail "there is no /etc/os-release on this machine, so nothing here can tell which install route Docker documents for it. Install Docker Engine and the compose plugin yourself: https://docs.docker.com/engine/install/"
  BRAIN_OS_ID="$(. /etc/os-release && printf "%s" "${ID:-} ${ID_LIKE:-}")"
  test "$(id -u)" -eq 0 || fail "installing Docker needs root and this is not a root shell. Run this again with sudo, or install Docker Engine and the compose plugin yourself: https://docs.docker.com/engine/install/"
  BRAIN_DOCKER_ROUTE=""
  for one in $BRAIN_OS_ID; do
    case "$one" in
      debian|ubuntu) BRAIN_DOCKER_ROUTE="apt $one" ;;
      almalinux|centos|fedora|rhel|rocky) BRAIN_DOCKER_ROUTE="dnf $one" ;;
      *) continue ;;
    esac
    break
  done
  test -n "$BRAIN_DOCKER_ROUTE" || fail "this is $BRAIN_OS_ID, and the routes Docker documents and this script knows are: debian ubuntu almalinux centos fedora rhel rocky. Install Docker Engine 24 or newer with the compose plugin by the route your distribution documents, then run this again: https://docs.docker.com/engine/install/"
  say "  installing Docker by the $BRAIN_DOCKER_ROUTE route Docker documents"
  case "$BRAIN_DOCKER_ROUTE" in
    apt*)
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y ca-certificates curl
      install -m 0755 -d "/etc/apt/keyrings"
      curl -fsSL "https://download.docker.com/linux/${BRAIN_DOCKER_ROUTE#apt }/gpg" -o "/etc/apt/keyrings/docker.asc"
      chmod a+r "/etc/apt/keyrings/docker.asc"
      printf "deb [arch=%s signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/%s %s stable\n" "$(dpkg --print-architecture)" "${BRAIN_DOCKER_ROUTE#apt }" "$(. /etc/os-release && printf "%s" "${VERSION_CODENAME:-}")" > "/etc/apt/sources.list.d/docker.list"
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ;;
    dnf*)
      dnf -y install dnf-plugins-core
      dnf -y config-manager --add-repo "https://download.docker.com/linux/${BRAIN_DOCKER_ROUTE#dnf }/docker-ce.repo"
      dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ;;
  esac
  systemctl enable --now docker || fail "Docker installed and its daemon would not start. Read the output of systemctl status docker, start it, then run this again. Nothing of this install has been written yet"
fi

# step 3 of 19: check the docker on this machine is new enough
say "step 3 of 19: check the docker on this machine is new enough"
BRAIN_ENGINE="$(docker version --format "{{.Server.Version}}" 2>/dev/null || true)"
if test -z "$BRAIN_ENGINE"; then
  refuse "the docker daemon on this machine is not answering, and 24.0 or newer is needed. the compose files use the Compose specification's \`deploy\` block, healthcheck \`start_period\` and \`depends_on\` conditions, and an older engine starts the dependent container before its dependency is ready"
elif ! at_least "$BRAIN_ENGINE" "24.0"; then
  refuse "this machine runs Docker Engine $BRAIN_ENGINE, and 24.0 or newer is needed. the compose files use the Compose specification's \`deploy\` block, healthcheck \`start_period\` and \`depends_on\` conditions, and an older engine starts the dependent container before its dependency is ready"
fi
BRAIN_COMPOSE_VERSION="$(docker compose version --short 2>/dev/null || true)"
if test -z "$BRAIN_COMPOSE_VERSION"; then
  refuse "this machine has no docker compose subcommand, which usually means the older docker-compose is installed instead, and 2.10 or newer is needed. Every memory ceiling in this deployment is written under deploy.resources.limits, and the v1 docker-compose tool ignores that block silently. An install on the old tool comes up healthy with every container unlimited and nothing anywhere says so, which turns the whole of brain.ops.wiring into a document about a deployment that is not running."
elif ! at_least "$BRAIN_COMPOSE_VERSION" "2.10"; then
  refuse "this machine runs compose $BRAIN_COMPOSE_VERSION, and 2.10 or newer is needed. Every memory ceiling in this deployment is written under deploy.resources.limits, and the v1 docker-compose tool ignores that block silently. An install on the old tool comes up healthy with every container unlimited and nothing anywhere says so, which turns the whole of brain.ops.wiring into a document about a deployment that is not running."
fi
test "$BRAIN_REFUSALS" -eq 0 || fail "the Docker on this machine is not one this deployment can run, for the reasons above. Nothing has been written"

# step 4 of 19: check the machine
say "step 4 of 19: check the machine"
command -v docker >/dev/null || fail "docker is not installed"
docker compose version >/dev/null 2>&1 || fail "docker compose v2 is not installed"

# step 5 of 19: check the machine is large enough
say "step 5 of 19: check the machine is large enough"
available=$(awk '/MemTotal/ {print int($2 / 1024)}' /proc/meminfo)
test "$available" -ge "$BRAIN_MEMORY_MIB" || fail "this profile needs $BRAIN_MEMORY_MIB MiB and this machine has $available MiB"

# step 6 of 19: create the install directory
if test -d "/opt/brain"; then
  say "step 6 of 19: create the install directory - already done, skipping"
else
  say "step 6 of 19: create the install directory"
  mkdir -p "/opt/brain"
fi

# step 7 of 19: download and unpack the release
if test -f "/opt/brain/RELEASE" && test "$(cat "/opt/brain/RELEASE")" = "$BRAIN_RELEASE"; then
  say "step 7 of 19: download and unpack the release - already done, skipping"
else
  say "step 7 of 19: download and unpack the release"
  curl -fsSL "$BRAIN_RELEASE_URL" -o "/opt/brain/release.tar.gz"
  tar -xzf "/opt/brain/release.tar.gz" -C "/opt/brain" --strip-components=1
  printf "%s\n" "$BRAIN_RELEASE" > "/opt/brain/RELEASE"
fi

# step 8 of 19: change into the release directory
say "step 8 of 19: change into the release directory"
cd "/opt/brain" || fail "the release did not unpack into /opt/brain"

# step 9 of 19: write the environment file from the template
if test -f "/opt/brain/.env"; then
  say "step 9 of 19: write the environment file from the template - already done, skipping"
else
  say "step 9 of 19: write the environment file from the template"
  test -f "/opt/brain/.env" || cp "/opt/brain/.env.example" "/opt/brain/.env"
fi

# step 10 of 19: pin the image this install runs
if grep -qxF "APP_IMAGE=$BRAIN_REPOSITORY:$BRAIN_RELEASE" "/opt/brain/.env"; then
  say "step 10 of 19: pin the image this install runs - already done, skipping"
else
  say "step 10 of 19: pin the image this install runs"
  umask 077
  {
    grep -v "^APP_IMAGE=" "/opt/brain/.env" || true
    printf "APP_IMAGE=%s\n" "$BRAIN_REPOSITORY:$BRAIN_RELEASE"
  } > "/opt/brain/.env.pinned"
  mv "/opt/brain/.env.pinned" "/opt/brain/.env"
fi

# step 11 of 19: create the settings the containers mount
if test -f "/opt/brain/settings/automation/egress.conf" && test -f "/opt/brain/settings/langfuse/clickhouse-memory.xml" && test -f "/opt/brain/settings/seaweedfs/provision.sh" && test -f "/opt/brain/settings/seaweedfs/s3.json"; then
  say "step 11 of 19: create the settings the containers mount - already done, skipping"
else
  say "step 11 of 19: create the settings the containers mount"
  mkdir -p "/opt/brain/settings/automation" "/opt/brain/settings/langfuse" "/opt/brain/settings/seaweedfs"
  test -f "/opt/brain/settings/automation/egress.conf" || cp "/opt/brain/ops/automation/egress.conf" "/opt/brain/settings/automation/egress.conf"
  test -f "/opt/brain/settings/langfuse/clickhouse-memory.xml" || cp "/opt/brain/ops/langfuse/clickhouse-memory.xml" "/opt/brain/settings/langfuse/clickhouse-memory.xml"
  test -f "/opt/brain/settings/seaweedfs/provision.sh" || cp "/opt/brain/ops/seaweedfs/provision.sh" "/opt/brain/settings/seaweedfs/provision.sh"
  test -f "/opt/brain/settings/seaweedfs/s3.json" || cp "/opt/brain/ops/seaweedfs/s3.json" "/opt/brain/settings/seaweedfs/s3.json"
fi

# step 12 of 19: mint this installation's secrets
if grep -q "^POSTGRES_PASSWORD=." "/opt/brain/.env"; then
  say "step 12 of 19: mint this installation's secrets - already done, skipping"
else
  say "step 12 of 19: mint this installation's secrets"
  umask 077
  {
    printf "POSTGRES_PASSWORD=%s\n" "$(openssl rand -hex 32)"
    printf "APP_ROLE_PASSWORD=%s\n" "$(openssl rand -hex 32)"
    printf "BRAIN_SETUP_SECRET=%s\n" "$(openssl rand -hex 32)"
    printf "BRAIN_SETUP_ISSUED_AT=%s\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >> "/opt/brain/.env"
fi

# step 13 of 19: pull the images this profile runs
if docker compose $BRAIN_COMPOSE_FILES images --quiet | grep -q .; then
  say "step 13 of 19: pull the images this profile runs - already done, skipping"
else
  say "step 13 of 19: pull the images this profile runs"
  docker compose $BRAIN_COMPOSE_FILES pull --quiet
fi

# step 14 of 19: start the database and wait for it
if docker compose $BRAIN_COMPOSE_FILES ps --status running --services | grep -qx db; then
  say "step 14 of 19: start the database and wait for it - already done, skipping"
else
  say "step 14 of 19: start the database and wait for it"
  docker compose $BRAIN_COMPOSE_FILES up -d db
  docker compose $BRAIN_COMPOSE_FILES exec -T db sh -c 'until pg_isready -U brain -d brain; do sleep 2; done'
fi

# step 15 of 19: create the databases the compose files do not
if ! docker compose $BRAIN_COMPOSE_FILES config --services | grep -qx langfuse-web || docker compose $BRAIN_COMPOSE_FILES exec -T db psql -tAc "select 1 from pg_database where datname = 'langfuse'" -U brain -d brain | grep -qx 1; then
  say "step 15 of 19: create the databases the compose files do not - already done, skipping"
else
  say "step 15 of 19: create the databases the compose files do not"
  if docker compose $BRAIN_COMPOSE_FILES config --services | grep -qx langfuse-web; then
    grep -q "^LANGFUSE_POSTGRES_PASSWORD=." "/opt/brain/.env" || fail "set LANGFUSE_POSTGRES_PASSWORD in /opt/brain/.env: this profile runs the trace ledger and it signs in with it"
    docker compose $BRAIN_COMPOSE_FILES exec -T db psql -tAc "select 1 from pg_roles where rolname = 'langfuse'" -U brain -d brain | grep -qx 1 || sed -n "s/^LANGFUSE_POSTGRES_PASSWORD=\(.*\)/create role langfuse login password '\1';/p" "/opt/brain/.env" | docker compose $BRAIN_COMPOSE_FILES exec -T db psql -v ON_ERROR_STOP=1 -U brain -d brain
    docker compose $BRAIN_COMPOSE_FILES exec -T db psql -tAc "select 1 from pg_database where datname = 'langfuse'" -U brain -d brain | grep -qx 1 || docker compose $BRAIN_COMPOSE_FILES exec -T db psql -v ON_ERROR_STOP=1 -U brain -d brain -c "create database langfuse owner langfuse"
  fi
fi

# step 16 of 19: start everything else
if test "$(docker compose $BRAIN_COMPOSE_FILES ps --status running --services | wc -l)" -ge "$BRAIN_SERVICES"; then
  say "step 16 of 19: start everything else - already done, skipping"
else
  say "step 16 of 19: start everything else"
  docker compose $BRAIN_COMPOSE_FILES up -d
fi

# step 17 of 19: wait for the application to report ready
say "step 17 of 19: wait for the application to report ready"
for _ in $(seq 1 60); do
  docker compose $BRAIN_COMPOSE_FILES exec -T app python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen("http://127.0.0.1:8000/health/ready",timeout=4).status==200 else 1)' && break
  sleep 5
done
docker compose $BRAIN_COMPOSE_FILES exec -T app python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen("http://127.0.0.1:8000/health/ready",timeout=4).status==200 else 1)' || fail "the application never reported ready"

# step 18 of 19: present the setup code, once
say "step 18 of 19: present the setup code, once"
printf "setup code: %s\n" "$(grep BRAIN_SETUP_SECRET "/opt/brain/.env" | cut -d= -f2)"
printf "%s\n" "Open the console and enter it on the first screen. It is required before anybody can claim this system."

# step 19 of 19: say where to go next
say "step 19 of 19: say where to go next"
say ""
if test -n "$BRAIN_CONSOLE_ADDRESS"; then
  printf "Open %s/first-run and enter the code above.\n" "${BRAIN_CONSOLE_ADDRESS%/}"
else
  say "No service in this deployment publishes a port, so the console answers on whatever address your reverse proxy sends to the app service. Open /first-run on that address and enter the code above."
fi
say "Sign in there first, then enter the code: it is held in that one browser tab and a reload loses it."
say "Until somebody does, this system has no administrator and whoever opens that address first becomes one."
say "docs/install/install.md, under The setup code, is the rest of it."

say "Done. The $BRAIN_PROFILE profile is running from $BRAIN_HOME."
